"""Transcript sync with revert detection."""

from __future__ import annotations

import json
import re
from collections.abc import Iterator
from dataclasses import dataclass, field
from pathlib import Path

from memory_service.ingestion.claude.jsonl_reader import iter_jsonl, iter_jsonl_reversed

# Patterns for cleaning user text (system noise from Claude Code)
_CAVEAT_PATTERN = re.compile(
    r"^Caveat: The messages below were generated by the user while running local "
    r"commands\. DO NOT respond to these messages or otherwise consider them in "
    r"your response unless the user explicitly asks you to\.\s*",
    re.DOTALL,
)
_LOCAL_STDOUT_PATTERN = re.compile(
    r"<local-command-stdout>[^<]*</local-command-stdout>\s*",
    re.DOTALL,
)


def _parse_command_xml(text: str) -> str | None:
    """Parse command XML and return command name if text is a command message.

    Uses XML parsing to be robust to element ordering. Only matches if the
    command XML is at the start of the message (after optional whitespace),
    preventing false matches on quoted command XML in user discussions.

    Returns:
        Command name (e.g., "/clear") if this is a command message, None otherwise.
    """
    import xml.etree.ElementTree as ET

    text = text.strip()
    if not text.startswith("<"):
        return None

    # Wrap in root element for parsing and find where command XML ends
    # We need to check that command XML is at the START, not embedded in prose
    try:
        # Try to parse just the command elements at the start
        # Command messages have: <command-name>, <command-message>, <command-args>
        # in any order, possibly with whitespace between them
        # nosec B314: Input is from Claude Code's own transcript logs, not untrusted
        root = ET.fromstring(f"<root>{text}</root>")  # nosec B314
    except ET.ParseError:
        return None

    # Check if the first few elements are command elements
    command_name = None
    has_command_message = False
    found_non_command = False

    for i, child in enumerate(root):
        if child.tag == "command-name":
            command_name = child.text
        elif child.tag == "command-message":
            has_command_message = True
        elif child.tag == "command-args":
            pass  # Optional, can be empty
        else:
            # Found a non-command element
            if i < 3:  # Command elements should be first
                found_non_command = True
            break

    # Only return command name if we found command elements at the start
    # and didn't find non-command content before them
    if command_name and has_command_message and not found_non_command:
        return command_name

    return None


@dataclass
class SessionStateHeader:
    """Header line of session state file."""

    document_id: str

    last_pid: int | None = None
    """PID of the Claude Code process for this session."""

    def to_json(self) -> dict[str, object]:
        result: dict[str, object] = {"document_id": self.document_id}
        if self.last_pid is not None:
            result["last_pid"] = self.last_pid
        return result

    @classmethod
    def from_json(cls, data: dict[str, object]) -> SessionStateHeader:
        doc_id = data.get("document_id")
        if not isinstance(doc_id, str):
            raise TypeError(f"document_id must be str, got {type(doc_id)}")
        last_pid = data.get("last_pid")
        if last_pid is not None and not isinstance(last_pid, int):
            raise TypeError(f"last_pid must be int or None, got {type(last_pid)}")
        return cls(document_id=doc_id, last_pid=last_pid)


@dataclass
class AppendEntry:
    """A single entry in the append log."""

    last_uuid: str
    """UUID of the last message in this append."""

    span_end: int
    """Document span position after this append."""

    def to_json(self) -> dict[str, object]:
        """Serialize to JSON-compatible dict."""
        return {"last_uuid": self.last_uuid, "span_end": self.span_end}

    @classmethod
    def from_json(cls, data: dict[str, object]) -> AppendEntry:
        """Deserialize from JSON dict."""
        last_uuid = data["last_uuid"]
        span_end = data["span_end"]
        if not isinstance(last_uuid, str):
            raise TypeError(f"last_uuid must be str, got {type(last_uuid)}")
        if not isinstance(span_end, int):
            raise TypeError(f"span_end must be int, got {type(span_end)}")
        return cls(last_uuid=last_uuid, span_end=span_end)


class AppendLog:
    """JSONL-based log of append operations."""

    def __init__(self, path: Path) -> None:
        self._path = path

    def append(self, entry: AppendEntry) -> None:
        """Append an entry to the log."""
        with open(self._path, "a") as f:
            f.write(json.dumps(entry.to_json()) + "\n")

    def last_entry(self) -> AppendEntry | None:
        """Get the last entry, or None if empty."""
        if not self._path.exists():
            return None

        # Read last line efficiently
        content = self._path.read_text().rstrip("\n")
        if not content:
            return None

        last_line = content.rsplit("\n", 1)[-1]
        return AppendEntry.from_json(json.loads(last_line))

    def truncate_to(self, last_uuid: str) -> None:
        """Remove all entries after the one with the given uuid."""
        entries = list(self)
        found_idx = None
        for i, entry in enumerate(entries):
            if entry.last_uuid == last_uuid:
                found_idx = i
                break

        if found_idx is None:
            raise ValueError(f"uuid {last_uuid!r} not found in append log")

        # Rewrite file with only entries up to and including found_idx
        with open(self._path, "w") as f:
            for entry in entries[: found_idx + 1]:
                f.write(json.dumps(entry.to_json()) + "\n")

    def __iter__(self) -> Iterator[AppendEntry]:
        """Iterate over all entries."""
        if not self._path.exists():
            return

        for record, _ in iter_jsonl(self._path):
            yield AppendEntry.from_json(record)


@dataclass
class SessionState:
    """Session state with header and append log."""

    header: SessionStateHeader
    entries: list[AppendEntry] = field(default_factory=list)

    @classmethod
    def load(cls, path: Path) -> SessionState | None:
        """Load session state from JSONL file.

        Returns None if file doesn't exist.
        """
        if not path.exists():
            return None

        lines = path.read_text().strip().split("\n")
        if not lines or not lines[0]:
            return None

        header = SessionStateHeader.from_json(json.loads(lines[0]))
        entries = [
            AppendEntry.from_json(json.loads(line)) for line in lines[1:] if line
        ]
        return cls(header=header, entries=entries)

    def save(self, path: Path) -> None:
        """Save session state to JSONL file."""
        path.parent.mkdir(parents=True, exist_ok=True)
        lines = [json.dumps(self.header.to_json())]
        lines.extend(json.dumps(entry.to_json()) for entry in self.entries)
        path.write_text("\n".join(lines) + "\n")

    def append_log(self) -> AppendLog:
        """Get an AppendLog view backed by this state's entries."""
        return _SessionAppendLog(self)


def _get_state_dir() -> Path:
    """Get the transcript state directory from environment or default."""
    import os

    state_dir_str = os.environ.get("RAGZOOM_STATE_DIR", "data/transcript-state")
    return Path(state_dir_str)


def get_state_path(document_id: str) -> Path:
    """Get the path to the state file for a document."""
    state_dir = _get_state_dir()
    state_dir.mkdir(parents=True, exist_ok=True)
    return state_dir / f"{document_id}.jsonl"


def set_session_pid(document_id: str, pid: int) -> None:
    """Set the PID for a session, creating state file if needed.

    Called by SessionStart hook to register the Claude Code PID before
    any tool calls. Preserves existing state fields if the file exists.
    """
    state_path = get_state_path(document_id)
    state = SessionState.load(state_path)
    if state is None:
        state = SessionState(header=SessionStateHeader(document_id=document_id))
    state.header.last_pid = pid
    state.save(state_path)


class _SessionAppendLog(AppendLog):
    """AppendLog backed by SessionState entries (in-memory)."""

    def __init__(self, state: SessionState) -> None:
        # Dummy path - not used for in-memory operations
        super().__init__(Path("/dev/null"))
        self._state = state

    def append(self, entry: AppendEntry) -> None:
        self._state.entries.append(entry)

    def last_entry(self) -> AppendEntry | None:
        if not self._state.entries:
            return None
        return self._state.entries[-1]

    def truncate_to(self, last_uuid: str) -> None:
        for i, entry in enumerate(self._state.entries):
            if entry.last_uuid == last_uuid:
                self._state.entries = self._state.entries[: i + 1]
                return
        raise ValueError(f"uuid {last_uuid!r} not found in append log")

    def __iter__(self) -> Iterator[AppendEntry]:
        return iter(self._state.entries)


def _get_ancestors(uuid: str, parent_map: dict[str, str | None]) -> set[str]:
    """Get all ancestors of a uuid (not including the uuid itself)."""
    ancestors: set[str] = set()
    current = parent_map.get(uuid)
    while current is not None:
        ancestors.add(current)
        current = parent_map.get(current)
    return ancestors


@dataclass
class StreamingAncestorResult:
    """Result from streaming common ancestor search."""

    common_ancestor: str | None
    """The common ancestor UUID, or None if branches are disjoint."""

    parent_of: dict[str, str | None]
    """Partial parent map containing all ancestors of both heads."""

    records_cache: dict[str, dict[str, object]]
    """Cached records for transcription."""


def stream_find_common_ancestor_and_records(
    transcript_path: Path,
    current_head: str,
    last_indexed: str | None,
) -> StreamingAncestorResult:
    """Stream backwards to find common ancestor, building parent_of and records cache.

    This is O(distance from end to common ancestor) instead of O(full transcript).
    Handles compaction bridging inline.

    Args:
        transcript_path: Path to the JSONL transcript
        current_head: UUID of the current transcript head
        last_indexed: UUID of the last indexed message, or None if empty

    Returns:
        StreamingAncestorResult with common ancestor, partial parent map, and records
    """
    reachable_from_current: set[str] = {current_head}
    reachable_from_last: set[str] = {last_indexed} if last_indexed else set()
    parent_of: dict[str, str | None] = {}
    records_cache: dict[str, dict[str, object]] = {}

    # Compaction bridging state
    # In reverse order: we see msg3 -> compact1 -> system1 -> msg2
    # system1 (parentUuid=None, seen after compaction) needs to be bridged to msg2
    saw_compaction = False
    pending_bridge: str | None = (
        None  # UUID that needs bridging to next regular message
    )

    for record in iter_jsonl_reversed(transcript_path):
        uuid = record.get("uuid")
        if not isinstance(uuid, str):
            continue

        parent = record.get("parentUuid")
        if parent is not None and not isinstance(parent, str):
            parent = None
        is_compact = bool(record.get("isCompactSummary"))

        records_cache[uuid] = record

        # Handle compaction summaries
        if is_compact:
            saw_compaction = True
            parent_of[uuid] = parent
            # Extend reachable sets through compaction
            if uuid in reachable_from_current and parent:
                reachable_from_current.add(parent)
            if uuid in reachable_from_last and parent:
                reachable_from_last.add(parent)
            continue

        # Handle messages with parentUuid=None
        if parent is None:
            if saw_compaction:
                # This message is followed by compaction (in forward order)
                # Bridge it to the next regular message we see
                pending_bridge = uuid
                saw_compaction = False
            parent_of[uuid] = None  # Tentative, may be updated below

        # Apply bridge: this non-compaction message is the target for pending bridge
        # We bridge to ANY non-compaction message (even with parentUuid=None)
        if pending_bridge is not None and pending_bridge != uuid:
            parent_of[pending_bridge] = uuid
            if pending_bridge in reachable_from_current:
                reachable_from_current.add(uuid)
            if pending_bridge in reachable_from_last:
                reachable_from_last.add(uuid)
            pending_bridge = None

        # Set parent for non-null parent messages
        if parent is not None:
            parent_of[uuid] = parent

        # Extend reachable sets
        actual_parent = parent_of.get(uuid)
        if uuid in reachable_from_current and actual_parent:
            reachable_from_current.add(actual_parent)
        if uuid in reachable_from_last and actual_parent:
            reachable_from_last.add(actual_parent)

        # Check for intersection (common ancestor)
        # The intersection contains the actual common ancestor UUID(s)
        intersection = reachable_from_current & reachable_from_last
        if intersection:
            # Return any element from intersection - they're all valid common ancestors
            # In the simple case (linear chain), there's only one
            common = next(iter(intersection))
            return StreamingAncestorResult(
                common_ancestor=common,
                parent_of=parent_of,
                records_cache=records_cache,
            )

    # No intersection = disjoint branches
    return StreamingAncestorResult(
        common_ancestor=None,
        parent_of=parent_of,
        records_cache=records_cache,
    )


def get_ancestor_chain(
    target: str, ancestor: str | None, parent_map: dict[str, str | None]
) -> list[str]:
    """Get ordered chain from ancestor to target (exclusive of ancestor).

    Args:
        target: The endpoint uuid
        ancestor: The starting point uuid (exclusive), or None for root
        parent_map: uuid -> parentUuid mapping

    Returns:
        List of uuids from ancestor's child to target, in forward order.
        Empty list if target == ancestor.

    Raises:
        ValueError: If ancestor is not actually an ancestor of target
    """
    if target == ancestor:
        return []

    # Walk backwards from target to ancestor, collecting the chain
    chain: list[str] = []
    current: str | None = target

    while current is not None and current != ancestor:
        chain.append(current)
        current = parent_map.get(current)

    # If ancestor is not None but we hit None without finding it, it's not an ancestor
    if ancestor is not None and current != ancestor:
        raise ValueError(f"{ancestor!r} is not an ancestor of {target!r}")

    # Reverse to get forward order (ancestor's child first, target last)
    chain.reverse()
    return chain


@dataclass
class SyncPlan:
    """Plan for syncing a transcript to the indexed document."""

    uuids_to_transcribe: list[str]
    """UUIDs to transcribe and append, in order."""

    truncate_to_span: int | None
    """If set, truncate document to this span before appending."""

    truncate_to_uuid: str | None
    """UUID of the valid prefix entry (for truncating append log)."""

    records_cache: dict[str, dict[str, object]] = field(default_factory=dict)
    """Cached records for transcription (from streaming, avoids second scan)."""


def compute_sync_plan_streaming(
    transcript_path: Path,
    current_head: str,
    append_log: AppendLog,
) -> SyncPlan:
    """Compute sync plan using streaming approach (O(distance) instead of O(n)).

    Args:
        transcript_path: Path to the JSONL transcript
        current_head: UUID of the current transcript head
        append_log: The append log tracking what we've indexed

    Returns:
        SyncPlan with records_cache populated for transcription
    """
    last_entry = append_log.last_entry()
    last_indexed = last_entry.last_uuid if last_entry else None

    # Already synced: nothing to do
    if last_indexed == current_head:
        return SyncPlan(
            uuids_to_transcribe=[],
            truncate_to_span=None,
            truncate_to_uuid=None,
        )

    # Stream backwards to find common ancestor and cache records
    result = stream_find_common_ancestor_and_records(
        transcript_path, current_head, last_indexed
    )

    # Empty append log: transcribe entire ancestor chain from root
    if last_entry is None:
        chain = get_ancestor_chain(current_head, None, result.parent_of)
        return SyncPlan(
            uuids_to_transcribe=chain,
            truncate_to_span=None,
            truncate_to_uuid=None,
            records_cache=result.records_cache,
        )

    # Disjoint branches: truncate everything and start fresh
    if result.common_ancestor is None:
        chain = get_ancestor_chain(current_head, None, result.parent_of)
        return SyncPlan(
            uuids_to_transcribe=chain,
            truncate_to_span=0,
            truncate_to_uuid=None,
            records_cache=result.records_cache,
        )

    # Find valid prefix entry (which entry contains the common ancestor)
    common_ancestors = _get_ancestors(result.common_ancestor, result.parent_of)
    common_ancestors.add(result.common_ancestor)

    valid_prefix: AppendEntry | None = None
    entries = list(append_log)
    for entry in reversed(entries):
        if entry.last_uuid in common_ancestors:
            valid_prefix = entry
            break

    if valid_prefix is None:
        # Shouldn't happen if common_ancestor was found, but handle gracefully
        chain = get_ancestor_chain(current_head, None, result.parent_of)
        return SyncPlan(
            uuids_to_transcribe=chain,
            truncate_to_span=0,
            truncate_to_uuid=None,
            records_cache=result.records_cache,
        )

    # Get chain from valid prefix to current head
    chain = get_ancestor_chain(current_head, valid_prefix.last_uuid, result.parent_of)

    # Determine if truncation is needed
    if valid_prefix.last_uuid == last_entry.last_uuid:
        # No revert, just append new messages
        return SyncPlan(
            uuids_to_transcribe=chain,
            truncate_to_span=None,
            truncate_to_uuid=None,
            records_cache=result.records_cache,
        )
    else:
        # Revert happened: truncate to valid prefix
        return SyncPlan(
            uuids_to_transcribe=chain,
            truncate_to_span=valid_prefix.span_end,
            truncate_to_uuid=valid_prefix.last_uuid,
            records_cache=result.records_cache,
        )


def get_compaction_uuid(transcript_path: Path) -> str | None:
    """Find the UUID just before the most recent compaction.

    Scans backwards from the end of the transcript for efficiency,
    since compaction is typically recent.

    Returns:
        UUID of the message just before compaction, or None if no compaction.
    """
    found_compaction = False
    for record in iter_jsonl_reversed(transcript_path):
        if record.get("isCompactSummary"):
            # Found compaction - the next UUID we see (going backwards)
            # is the one just before the compaction in chronological order
            found_compaction = True
            continue
        uuid = record.get("uuid")
        if isinstance(uuid, str):
            if found_compaction:
                return uuid
    return None


def get_current_head(transcript_path: Path) -> str | None:
    """Get the UUID of the most recent message in the transcript.

    Scans backwards from the end for efficiency, since the head is at the end.
    Returns None if no messages with uuid found.
    """
    for record in iter_jsonl_reversed(transcript_path):
        if record.get("isCompactSummary"):
            continue
        uuid = record.get("uuid")
        if isinstance(uuid, str):
            return uuid
    return None


def transcribe_uuid_from_map(
    uuid: str,
    records_by_uuid: dict[str, dict[str, object]],
) -> str:
    """Transcribe a single UUID using a pre-built records map.

    Args:
        uuid: The UUID to transcribe
        records_by_uuid: Pre-built UUID -> record lookup

    Returns:
        Transcribed text, or empty string if UUID not found or produces no text
    """
    if uuid not in records_by_uuid:
        return ""
    record = records_by_uuid[uuid]
    chunk = _transcribe_record(record)
    return chunk if chunk else ""


def _is_tool_only_assistant(record: dict[str, object]) -> bool:
    """Check if record is an assistant message with only tool use (no text)."""
    if record.get("type") != "assistant":
        return False
    text, tools = _extract_assistant_content(record)
    return bool(tools) and not text.strip()


def _format_tool_batch(tools: list[str]) -> str:
    """Format a batch of tools into a single message."""
    count = len(tools)
    tools_str = ", ".join(tools)
    return f"[Used {count} tool{'s' if count > 1 else ''}: {tools_str}]"


def _is_command_invocation(record: dict[str, object]) -> str | None:
    """Check if record is a command invocation, return command name if so.

    Only matches if the command XML is at the start of the message (after
    optional caveat boilerplate). This prevents matching quoted command XML
    in user messages that discuss commands.
    """
    if record.get("type") != "user":
        return None
    text = _extract_user_text_raw(record)
    # Strip caveat boilerplate first, then check if command XML is at the start
    text = _CAVEAT_PATTERN.sub("", text)
    return _parse_command_xml(text)


def _extract_user_text_raw(record: dict[str, object]) -> str:
    """Extract raw text from a user message without cleaning."""
    message = record.get("message", {})
    if not isinstance(message, dict):
        return str(message)

    content = message.get("content", "")
    if isinstance(content, str):
        return content

    if isinstance(content, list):
        texts = []
        for block in content:
            if isinstance(block, dict) and block.get("type") == "text":
                texts.append(str(block.get("text", "")))
            elif isinstance(block, str):
                texts.append(block)
        return "".join(texts)

    return str(content)


def transcribe_uuids_from_map(
    uuids: list[str],
    records_by_uuid: dict[str, dict[str, object]],
) -> str:
    """Transcribe UUIDs using a pre-built records map with tool batching.

    Consecutive tool-only assistant messages are batched into a single
    "[Used N tools: ...]" line. Command invocations are simplified to
    "[User issued /foo command]" and their expansion messages are skipped.

    Args:
        uuids: UUIDs to transcribe, in order
        records_by_uuid: Pre-built UUID -> record lookup

    Returns:
        Concatenated transcript text
    """
    if not uuids:
        return ""

    # Build set of command UUIDs so we can skip their child user messages
    command_uuids: set[str] = set()
    for uuid in uuids:
        record = records_by_uuid.get(uuid)
        if record is not None and _is_command_invocation(record) is not None:
            command_uuids.add(uuid)

    chunks: list[str] = []
    pending_tools: list[str] = []

    for uuid in uuids:
        record = records_by_uuid.get(uuid)
        if record is None:
            continue

        # Skip tool results
        if record.get("type") == "user" and "toolUseResult" in record:
            continue

        # Check if this is a user message whose parent is a command invocation
        parent_uuid = record.get("parentUuid")
        if (
            record.get("type") == "user"
            and isinstance(parent_uuid, str)
            and parent_uuid in command_uuids
        ):
            # Skip command expansion/output messages
            continue

        # Check if this is a command invocation
        cmd_name = _is_command_invocation(record)
        if cmd_name is not None:
            if pending_tools:
                chunks.append(_format_tool_batch(pending_tools))
                pending_tools = []
            chunks.append(f"[User issued {cmd_name} command]")
            continue

        if _is_tool_only_assistant(record):
            _, tools = _extract_assistant_content(record)
            pending_tools.extend(tools)
        else:
            if pending_tools:
                chunks.append(_format_tool_batch(pending_tools))
                pending_tools = []

            chunk = _transcribe_record(record)
            if chunk:
                chunks.append(chunk)

    if pending_tools:
        chunks.append(_format_tool_batch(pending_tools))

    return "\n\n".join(chunks)


def _transcribe_record(record: dict[str, object]) -> str | None:
    """Transcribe a single record to readable text."""
    record_type = record.get("type")

    if record_type == "user":
        # Skip tool results
        if "toolUseResult" in record:
            return None
        text = _extract_user_text(record)
        if text.strip():
            return f"[USER]\n{text}"

    elif record_type == "assistant":
        text, tools = _extract_assistant_content(record)
        parts: list[str] = []
        if text.strip():
            parts.append(f"[ASSISTANT]\n{text}")
        if tools:
            tool_count = len(tools)
            tools_str = ", ".join(tools)
            parts.append(
                f"[Used {tool_count} tool{'s' if tool_count > 1 else ''}: {tools_str}]"
            )
        if parts:
            return "\n\n".join(parts)

    return None


def _clean_user_text(text: str) -> str:
    """Clean system noise from user text, transforming commands to simple format.

    Command messages (those starting with caveat boilerplate, command XML, or
    local-command-stdout) are cleaned appropriately. Regular user messages are
    returned as-is to preserve any quoted command examples or discussions.
    """
    text = text.strip()

    # Check for and strip caveat boilerplate (only at start of message)
    stripped = _CAVEAT_PATTERN.sub("", text)
    is_command_context = stripped != text
    if is_command_context:
        text = stripped.strip()

    # Check for command XML (at start of remaining text)
    cmd_name = _parse_command_xml(text)
    if cmd_name is not None:
        return cmd_name

    # Check if message starts with local-command-stdout (command output message)
    if text.startswith("<local-command-stdout>"):
        is_command_context = True

    # If we're in command context, clean up stdout tags
    if is_command_context:
        text = _LOCAL_STDOUT_PATTERN.sub("", text)
        return text.strip()

    # Regular user message - return unchanged (preserve quoted content)
    return text


def _extract_user_text(record: dict[str, object]) -> str:
    """Extract text content from a user message."""
    message = record.get("message", {})
    if not isinstance(message, dict):
        return _clean_user_text(str(message))

    content = message.get("content", "")
    if isinstance(content, str):
        return _clean_user_text(content)

    if isinstance(content, list):
        texts = []
        for block in content:
            if isinstance(block, dict) and block.get("type") == "text":
                texts.append(str(block.get("text", "")))
            elif isinstance(block, str):
                texts.append(block)
        return _clean_user_text("".join(texts))

    return _clean_user_text(str(content))


def _format_tool_summary(name: str, input_data: dict[str, object]) -> str:
    """Format a tool invocation as Name(summary)."""
    # Extract a brief summary based on tool type
    summary = ""
    if name == "Bash":
        cmd = input_data.get("command", "")
        if isinstance(cmd, str):
            # Truncate long commands
            summary = cmd[:40] + "..." if len(cmd) > 43 else cmd
    elif name == "Read":
        path = input_data.get("file_path", "")
        if isinstance(path, str):
            summary = path
    elif name == "Grep":
        pattern = input_data.get("pattern", "")
        if isinstance(pattern, str):
            summary = pattern[:30] + "..." if len(pattern) > 33 else pattern
    elif name == "Glob":
        pattern = input_data.get("pattern", "")
        if isinstance(pattern, str):
            summary = pattern
    elif name == "Edit":
        path = input_data.get("file_path", "")
        if isinstance(path, str):
            summary = path
    elif name == "Write":
        path = input_data.get("file_path", "")
        if isinstance(path, str):
            summary = path
    elif name == "Task":
        desc = input_data.get("description", "")
        if isinstance(desc, str):
            summary = desc
    else:
        # For other tools, try common input keys
        for key in ("query", "url", "path", "file_path", "pattern"):
            val = input_data.get(key, "")
            if isinstance(val, str) and val:
                summary = val[:30] + "..." if len(val) > 33 else val
                break

    if summary:
        return f"{name}({summary})"
    return name


def _extract_assistant_content(
    record: dict[str, object],
) -> tuple[str, list[str]]:
    """Extract text and tool summaries from an assistant message.

    Returns:
        Tuple of (text content, list of tool summaries like "Bash(git status)")
    """
    message = record.get("message", {})
    if not isinstance(message, dict):
        return str(message), []

    content = message.get("content", [])
    if not isinstance(content, list):
        return str(content), []

    texts: list[str] = []
    tools: list[str] = []

    for block in content:
        if not isinstance(block, dict):
            continue

        block_type = block.get("type")
        if block_type == "text":
            text = block.get("text", "")
            if isinstance(text, str) and text.strip():
                texts.append(text)
        elif block_type == "tool_use":
            name = block.get("name", "unknown")
            if not isinstance(name, str):
                name = "unknown"
            input_data = block.get("input", {})
            if not isinstance(input_data, dict):
                input_data = {}
            tools.append(_format_tool_summary(name, input_data))

    return "\n\n".join(texts), tools


@dataclass
class SyncResult:
    """Result from executing a sync operation."""

    document_id: str
    truncated: bool
    truncate_span: int | None
    appended_uuids: list[str]
    new_span_end: int
    truncate_byte_offset: int | None = None  # For server-side storage truncation


def execute_sync(
    transcript_path: Path,
    state_path: Path,
    client: object,
) -> SyncResult:
    """Execute a complete sync operation.

    Args:
        transcript_path: Path to the JSONL transcript
        state_path: Path to the session state file
        client: RagZoom client with append() and truncate() methods

    Returns:
        SyncResult describing what was done
    """
    # Load or create session state
    state = SessionState.load(state_path)
    if state is None:
        # Generate document_id from transcript filename
        document_id = transcript_path.stem
        state = SessionState(header=SessionStateHeader(document_id=document_id))

    document_id = state.header.document_id

    # Get current head
    current_head = get_current_head(transcript_path)
    if current_head is None:
        # Empty transcript, nothing to sync
        return SyncResult(
            document_id=document_id,
            truncated=False,
            truncate_span=None,
            appended_uuids=[],
            new_span_end=0,
        )

    # Compute sync plan using streaming (O(distance) instead of O(n))
    append_log = state.append_log()
    plan = compute_sync_plan_streaming(transcript_path, current_head, append_log)

    # Nothing to do
    if not plan.uuids_to_transcribe and plan.truncate_to_span is None:
        last_entry = append_log.last_entry()
        span_end = last_entry.span_end if last_entry else 0
        state.save(state_path)
        return SyncResult(
            document_id=document_id,
            truncated=False,
            truncate_span=None,
            appended_uuids=[],
            new_span_end=span_end,
        )

    truncated = False
    truncate_span: int | None = None

    # Execute truncation if needed
    if plan.truncate_to_span is not None:
        truncate_method = getattr(client, "truncate")
        truncate_method(document_id, plan.truncate_to_span)
        truncated = True
        truncate_span = plan.truncate_to_span

        # Truncate the append log
        if plan.truncate_to_uuid is not None:
            append_log.truncate_to(plan.truncate_to_uuid)
        else:
            # Disjoint branches - clear the state entries
            state.entries = []

    # Transcribe and append UUIDs, batching per compaction segment
    appended_uuids: list[str] = []
    new_span_end = 0
    if plan.uuids_to_transcribe:
        # Use records cached during streaming (avoids second O(n) scan)
        records_by_uuid = plan.records_cache

        # Split UUIDs into segments at turn boundaries
        # A turn = user messages + subsequent assistant/tool messages
        # New turn starts when user message follows a non-user message
        segments: list[list[str]] = []
        current_segment: list[str] = []
        prev_was_user = False

        for uuid in plan.uuids_to_transcribe:
            record = records_by_uuid.get(uuid)

            # Skip UUIDs not in records map (compaction summaries are filtered out)
            if record is None:
                continue

            # Check if this is a user message (excluding tool results)
            is_user_message = (
                record.get("type") == "user" and "toolUseResult" not in record
            )

            # Start new segment when user message follows non-user message
            if is_user_message and not prev_was_user and current_segment:
                segments.append(current_segment)
                current_segment = []

            current_segment.append(uuid)
            prev_was_user = is_user_message

        # Don't forget the last segment
        if current_segment:
            segments.append(current_segment)

        # Transcribe each segment and collect for batch append
        segment_texts: list[str] = []
        segment_last_uuids: list[str] = []  # Last uuid from each segment

        for segment_uuids in segments:
            # Use batching transcription for tool consolidation
            combined_text = transcribe_uuids_from_map(segment_uuids, records_by_uuid)

            if combined_text:
                segment_texts.append(combined_text)
                # Track the last uuid that produced content
                segment_appended_uuids = [
                    u
                    for u in segment_uuids
                    if u in records_by_uuid
                    and not (
                        records_by_uuid[u].get("type") == "user"
                        and "toolUseResult" in records_by_uuid[u]
                    )
                ]
                if segment_appended_uuids:
                    segment_last_uuids.append(segment_appended_uuids[-1])
                    appended_uuids.extend(segment_appended_uuids)

        # Use batch_append to send all segments in one gRPC call
        if segment_texts:
            batch_append_method = getattr(client, "batch_append")
            result = batch_append_method(document_id, segment_texts)
            final_span_end = getattr(result, "span_end", 0)

            # Record an append log entry per segment for revert detection granularity
            # Calculate cumulative span positions for each segment
            span_cursor = getattr(result, "span_start", 0)
            for i, (text, last_uuid) in enumerate(
                zip(segment_texts, segment_last_uuids)
            ):
                span_cursor += len(text)
                append_log.append(
                    AppendEntry(
                        last_uuid=last_uuid,
                        span_end=span_cursor,
                    )
                )
            new_span_end = final_span_end

        if not appended_uuids:
            last_entry = append_log.last_entry()
            new_span_end = last_entry.span_end if last_entry else 0
    else:
        last_entry = append_log.last_entry()
        new_span_end = last_entry.span_end if last_entry else 0

    # Save state
    state.save(state_path)

    return SyncResult(
        document_id=document_id,
        truncated=truncated,
        truncate_span=truncate_span,
        appended_uuids=appended_uuids,
        new_span_end=new_span_end,
    )


def _iter_jsonl_from_bytes(
    content: bytes, start_offset: int = 0
) -> Iterator[tuple[dict[str, object], int]]:
    """Iterate over JSONL records from bytes.

    Args:
        content: JSONL content as bytes.
        start_offset: Byte offset to start reading from.

    Yields:
        Tuples of (record, end_offset) where end_offset is the byte position
        after the newline following this record.
    """
    pos = start_offset
    while pos < len(content):
        # Find next newline
        newline_pos = content.find(b"\n", pos)
        if newline_pos == -1:
            # Last line without newline
            line = content[pos:]
            end_pos = len(content)
        else:
            line = content[pos:newline_pos]
            end_pos = newline_pos + 1

        line_str = line.decode("utf-8").strip()
        if line_str:
            yield json.loads(line_str), end_pos

        pos = end_pos


def _iter_jsonl_reversed_from_bytes(content: bytes) -> Iterator[dict[str, object]]:
    """Iterate over JSONL records from bytes in reverse order.

    Args:
        content: JSONL content as bytes.

    Yields:
        Parsed JSON objects, from last record to first.
    """
    if not content:
        return

    # Split into lines and yield in reverse
    lines = content.split(b"\n")
    for line in reversed(lines):
        line_str = line.decode("utf-8").strip()
        if line_str:
            yield json.loads(line_str)


def _get_current_head_from_bytes(content: bytes) -> str | None:
    """Get the UUID of the most recent non-compaction message from bytes."""
    for record in _iter_jsonl_reversed_from_bytes(content):
        if record.get("isCompactSummary"):
            continue
        uuid = record.get("uuid")
        if isinstance(uuid, str):
            return uuid
    return None


def _build_parent_map_from_bytes(content: bytes) -> dict[str, str | None]:
    """Build a uuid -> parentUuid map from bytes content."""
    parent_map: dict[str, str | None] = {}
    records: list[tuple[str, str | None, bool]] = []

    for record, _ in _iter_jsonl_from_bytes(content):
        uuid = record.get("uuid")
        if isinstance(uuid, str):
            parent_uuid = record.get("parentUuid")
            if parent_uuid is not None and not isinstance(parent_uuid, str):
                continue
            is_compact = bool(record.get("isCompactSummary"))
            records.append((uuid, parent_uuid, is_compact))

    # Same bridging logic as build_parent_map
    last_regular_uuid: str | None = None

    for i, (uuid, parent_uuid, is_compact) in enumerate(records):
        if parent_uuid is None and not is_compact:
            is_followed_by_compact = False
            for j in range(i + 1, len(records)):
                _, _, next_is_compact = records[j]
                if next_is_compact:
                    is_followed_by_compact = True
                    break
                break

            if is_followed_by_compact and last_regular_uuid is not None:
                parent_map[uuid] = last_regular_uuid
            else:
                parent_map[uuid] = None
        else:
            parent_map[uuid] = parent_uuid

        if not is_compact:
            last_regular_uuid = uuid

    return parent_map


def _build_records_map_from_bytes(
    content: bytes, uuids: set[str]
) -> dict[str, dict[str, object]]:
    """Build a map of uuid -> record for the given UUIDs from bytes."""
    records_map: dict[str, dict[str, object]] = {}
    for record, _ in _iter_jsonl_from_bytes(content):
        uuid = record.get("uuid")
        if isinstance(uuid, str) and uuid in uuids:
            if not record.get("isCompactSummary"):
                records_map[uuid] = record
    return records_map


@dataclass
class BytesSyncState:
    """Server-side sync state for a session."""

    append_log: list[AppendEntry] = field(default_factory=list)

    def last_entry(self) -> AppendEntry | None:
        return self.append_log[-1] if self.append_log else None


def execute_sync_from_bytes(
    session_id: str,
    jsonl_content: bytes,
    previous_byte_offset: int,
    client: object,
) -> SyncResult:
    """Execute sync from in-memory JSONL bytes (for server-side processing).

    This version is used when the server stores the JSONL and processes it
    directly, rather than reading from a file path.

    Args:
        session_id: The session ID (used as document_id)
        jsonl_content: Full JSONL content as bytes
        previous_byte_offset: Byte offset where previous sync ended
        client: RagZoom client with append() and truncate() methods

    Returns:
        SyncResult describing what was done
    """
    import logging
    import time

    logger = logging.getLogger(__name__)
    t0 = time.perf_counter()
    document_id = session_id

    logger.info(
        "[TIMING] execute_sync_from_bytes start: content_bytes=%d prev_offset=%d",
        len(jsonl_content),
        previous_byte_offset,
    )

    # Get current head from full content
    current_head = _get_current_head_from_bytes(jsonl_content)
    t_head = time.perf_counter()
    if current_head is None:
        return SyncResult(
            document_id=document_id,
            truncated=False,
            truncate_span=None,
            appended_uuids=[],
            new_span_end=0,
        )

    # Build parent map from full content
    parent_map = _build_parent_map_from_bytes(jsonl_content)
    t_parent_map = time.perf_counter()

    # Build append log from previously synced content
    # We need to reconstruct what was synced before
    sync_state = BytesSyncState()
    if previous_byte_offset > 0:
        # Parse the previously synced portion to rebuild state
        prev_content = jsonl_content[:previous_byte_offset]
        prev_head = _get_current_head_from_bytes(prev_content)
        if prev_head:
            # We don't have the exact append log, but we can approximate
            # by treating the previous content as one big append
            # This is a simplification - in practice the server should
            # store the append log alongside the JSONL
            sync_state.append_log.append(
                AppendEntry(last_uuid=prev_head, span_end=previous_byte_offset)
            )

    # Create an append log view for compute_sync_plan
    class _BytesAppendLog(AppendLog):
        def __init__(self, state: BytesSyncState) -> None:
            super().__init__(Path("/dev/null"))
            self._state = state

        def append(self, entry: AppendEntry) -> None:
            self._state.append_log.append(entry)

        def last_entry(self) -> AppendEntry | None:
            return self._state.last_entry()

        def truncate_to(self, last_uuid: str) -> None:
            for i, entry in enumerate(self._state.append_log):
                if entry.last_uuid == last_uuid:
                    self._state.append_log = self._state.append_log[: i + 1]
                    return
            raise ValueError(f"uuid {last_uuid!r} not found in append log")

        def __iter__(self) -> Iterator[AppendEntry]:
            return iter(self._state.append_log)

    append_log = _BytesAppendLog(sync_state)

    # Compute sync plan
    plan = compute_sync_plan(current_head, append_log, parent_map)
    t_plan = time.perf_counter()

    logger.info(
        "[TIMING] parse phase: head=%.3fs parent_map=%.3fs plan=%.3fs "
        "uuids_to_transcribe=%d",
        t_head - t0,
        t_parent_map - t_head,
        t_plan - t_parent_map,
        len(plan.uuids_to_transcribe),
    )

    # Nothing to do
    if not plan.uuids_to_transcribe and plan.truncate_to_span is None:
        last_entry = append_log.last_entry()
        span_end = last_entry.span_end if last_entry else 0
        return SyncResult(
            document_id=document_id,
            truncated=False,
            truncate_span=None,
            appended_uuids=[],
            new_span_end=span_end,
        )

    truncated = False
    truncate_span: int | None = None
    truncate_byte_offset: int | None = None

    # Execute truncation if needed
    if plan.truncate_to_span is not None:
        truncate_method = getattr(client, "truncate")
        truncate_method(document_id, plan.truncate_to_span)
        truncated = True
        truncate_span = plan.truncate_to_span

        # Find byte offset for the truncation point
        if plan.truncate_to_uuid is not None:
            for entry in sync_state.append_log:
                if entry.last_uuid == plan.truncate_to_uuid:
                    truncate_byte_offset = entry.span_end
                    break
            append_log.truncate_to(plan.truncate_to_uuid)
        else:
            truncate_byte_offset = 0
            sync_state.append_log = []

    # Transcribe and append
    appended_uuids: list[str] = []
    new_span_end = 0

    if plan.uuids_to_transcribe:
        records_by_uuid = _build_records_map_from_bytes(
            jsonl_content, set(plan.uuids_to_transcribe)
        )
        t_records = time.perf_counter()

        # Segment UUIDs at turn boundaries
        segments: list[list[str]] = []
        current_segment: list[str] = []
        prev_was_user = False

        for uuid in plan.uuids_to_transcribe:
            record = records_by_uuid.get(uuid)
            if record is None:
                continue

            is_user_message = (
                record.get("type") == "user" and "toolUseResult" not in record
            )

            if is_user_message and not prev_was_user and current_segment:
                segments.append(current_segment)
                current_segment = []

            current_segment.append(uuid)
            prev_was_user = is_user_message

        if current_segment:
            segments.append(current_segment)

        # Transcribe and append
        segment_texts: list[str] = []
        segment_last_uuids: list[str] = []

        for segment_uuids in segments:
            combined_text = transcribe_uuids_from_map(segment_uuids, records_by_uuid)

            if combined_text:
                segment_texts.append(combined_text)
                segment_appended_uuids = [
                    u
                    for u in segment_uuids
                    if u in records_by_uuid
                    and not (
                        records_by_uuid[u].get("type") == "user"
                        and "toolUseResult" in records_by_uuid[u]
                    )
                ]
                if segment_appended_uuids:
                    segment_last_uuids.append(segment_appended_uuids[-1])
                    appended_uuids.extend(segment_appended_uuids)

        t_transcribe = time.perf_counter()
        logger.info(
            "[TIMING] transcribe phase: records_map=%.3fs transcribe=%.3fs "
            "segments=%d",
            t_records - t_plan,
            t_transcribe - t_records,
            len(segment_texts),
        )

        if segment_texts:
            batch_append_method = getattr(client, "batch_append")
            result = batch_append_method(document_id, segment_texts)
            new_span_end = getattr(result, "span_end", 0)
            t_append = time.perf_counter()
            logger.info(
                "[TIMING] batch_append complete: %.3fs segments=%d",
                t_append - t_transcribe,
                len(segment_texts),
            )
    else:
        last_entry = append_log.last_entry()
        new_span_end = last_entry.span_end if last_entry else 0

    t_end = time.perf_counter()
    logger.info(
        "[TIMING] execute_sync_from_bytes complete: total=%.3fs appended=%d",
        t_end - t0,
        len(appended_uuids),
    )

    return SyncResult(
        document_id=document_id,
        truncated=truncated,
        truncate_span=truncate_span,
        appended_uuids=appended_uuids,
        new_span_end=new_span_end,
        truncate_byte_offset=truncate_byte_offset,
    )
