# mypy: ignore-errors
# ruff: noqa
# jscpd:ignore-start
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:  # pragma: no cover
    import dynamic_summary_pb2 as dynamic__summary__pb2
except ModuleNotFoundError:  # pragma: no cover
    from . import dynamic_summary_pb2 as dynamic__summary__pb2


GRPC_GENERATED_VERSION = "1.75.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in dynamic_summary_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class IndexerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IndexDocument = channel.unary_unary(
            "/ragzoom.rpc.IndexerService/IndexDocument",
            request_serializer=dynamic__summary__pb2.IndexDocumentRequest.SerializeToString,
            response_deserializer=dynamic__summary__pb2.IndexDocumentResponse.FromString,
            _registered_method=True,
        )
        self.AppendText = channel.unary_unary(
            "/ragzoom.rpc.IndexerService/AppendText",
            request_serializer=dynamic__summary__pb2.AppendTextRequest.SerializeToString,
            response_deserializer=dynamic__summary__pb2.AppendTextResponse.FromString,
            _registered_method=True,
        )


class IndexerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IndexDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AppendText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_IndexerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "IndexDocument": grpc.unary_unary_rpc_method_handler(
            servicer.IndexDocument,
            request_deserializer=dynamic__summary__pb2.IndexDocumentRequest.FromString,
            response_serializer=dynamic__summary__pb2.IndexDocumentResponse.SerializeToString,
        ),
        "AppendText": grpc.unary_unary_rpc_method_handler(
            servicer.AppendText,
            request_deserializer=dynamic__summary__pb2.AppendTextRequest.FromString,
            response_serializer=dynamic__summary__pb2.AppendTextResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "ragzoom.rpc.IndexerService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "ragzoom.rpc.IndexerService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class IndexerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IndexDocument(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ragzoom.rpc.IndexerService/IndexDocument",
            dynamic__summary__pb2.IndexDocumentRequest.SerializeToString,
            dynamic__summary__pb2.IndexDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AppendText(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ragzoom.rpc.IndexerService/AppendText",
            dynamic__summary__pb2.AppendTextRequest.SerializeToString,
            dynamic__summary__pb2.AppendTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class RetrievalServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Retrieve = channel.unary_unary(
            "/ragzoom.rpc.RetrievalService/Retrieve",
            request_serializer=dynamic__summary__pb2.RetrieveRequest.SerializeToString,
            response_deserializer=dynamic__summary__pb2.RetrieveResponse.FromString,
            _registered_method=True,
        )
        self.ExecuteQuery = channel.unary_unary(
            "/ragzoom.rpc.RetrievalService/ExecuteQuery",
            request_serializer=dynamic__summary__pb2.ExecuteQueryRequest.SerializeToString,
            response_deserializer=dynamic__summary__pb2.ExecuteQueryResponse.FromString,
            _registered_method=True,
        )


class RetrievalServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ExecuteQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RetrievalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Retrieve": grpc.unary_unary_rpc_method_handler(
            servicer.Retrieve,
            request_deserializer=dynamic__summary__pb2.RetrieveRequest.FromString,
            response_serializer=dynamic__summary__pb2.RetrieveResponse.SerializeToString,
        ),
        "ExecuteQuery": grpc.unary_unary_rpc_method_handler(
            servicer.ExecuteQuery,
            request_deserializer=dynamic__summary__pb2.ExecuteQueryRequest.FromString,
            response_serializer=dynamic__summary__pb2.ExecuteQueryResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "ragzoom.rpc.RetrievalService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "ragzoom.rpc.RetrievalService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class RetrievalService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Retrieve(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ragzoom.rpc.RetrievalService/Retrieve",
            dynamic__summary__pb2.RetrieveRequest.SerializeToString,
            dynamic__summary__pb2.RetrieveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ExecuteQuery(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ragzoom.rpc.RetrievalService/ExecuteQuery",
            dynamic__summary__pb2.ExecuteQueryRequest.SerializeToString,
            dynamic__summary__pb2.ExecuteQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class WorkerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunWorkers = channel.unary_stream(
            "/ragzoom.rpc.WorkerService/RunWorkers",
            request_serializer=dynamic__summary__pb2.RunWorkersRequest.SerializeToString,
            response_deserializer=dynamic__summary__pb2.RunWorkersResponse.FromString,
            _registered_method=True,
        )
        self.GetDocument = channel.unary_unary(
            "/ragzoom.rpc.WorkerService/GetDocument",
            request_serializer=dynamic__summary__pb2.GetDocumentRequest.SerializeToString,
            response_deserializer=dynamic__summary__pb2.GetDocumentResponse.FromString,
            _registered_method=True,
        )


class WorkerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunWorkers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "RunWorkers": grpc.unary_stream_rpc_method_handler(
            servicer.RunWorkers,
            request_deserializer=dynamic__summary__pb2.RunWorkersRequest.FromString,
            response_serializer=dynamic__summary__pb2.RunWorkersResponse.SerializeToString,
        ),
        "GetDocument": grpc.unary_unary_rpc_method_handler(
            servicer.GetDocument,
            request_deserializer=dynamic__summary__pb2.GetDocumentRequest.FromString,
            response_serializer=dynamic__summary__pb2.GetDocumentResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "ragzoom.rpc.WorkerService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "ragzoom.rpc.WorkerService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class WorkerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunWorkers(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/ragzoom.rpc.WorkerService/RunWorkers",
            dynamic__summary__pb2.RunWorkersRequest.SerializeToString,
            dynamic__summary__pb2.RunWorkersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetDocument(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ragzoom.rpc.WorkerService/GetDocument",
            dynamic__summary__pb2.GetDocumentRequest.SerializeToString,
            dynamic__summary__pb2.GetDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


# jscpd:ignore-end
