# mypy: ignore-errors
# ruff: noqa
# jscpd:ignore-start
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:  # pragma: no cover
    import dynamic_summary_pb2 as dynamic__summary__pb2
except ModuleNotFoundError:  # pragma: no cover
    from . import dynamic_summary_pb2 as dynamic__summary__pb2


GRPC_GENERATED_VERSION = "1.75.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in dynamic_summary_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class IndexerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IndexDocument = channel.unary_unary(
            "/ragzoom.rpc.IndexerService/IndexDocument",
            request_serializer=dynamic__summary__pb2.IndexDocumentRequest.SerializeToString,
            response_deserializer=dynamic__summary__pb2.IndexDocumentResponse.FromString,
            _registered_method=True,
        )
        self.AppendText = channel.unary_unary(
            "/ragzoom.rpc.IndexerService/AppendText",
            request_serializer=dynamic__summary__pb2.AppendTextRequest.SerializeToString,
            response_deserializer=dynamic__summary__pb2.AppendTextResponse.FromString,
            _registered_method=True,
        )
        self.BatchAppendText = channel.unary_unary(
            "/ragzoom.rpc.IndexerService/BatchAppendText",
            request_serializer=dynamic__summary__pb2.BatchAppendTextRequest.SerializeToString,
            response_deserializer=dynamic__summary__pb2.BatchAppendTextResponse.FromString,
            _registered_method=True,
        )
        self.TruncateDocument = channel.unary_unary(
            "/ragzoom.rpc.IndexerService/TruncateDocument",
            request_serializer=dynamic__summary__pb2.TruncateDocumentRequest.SerializeToString,
            response_deserializer=dynamic__summary__pb2.TruncateDocumentResponse.FromString,
            _registered_method=True,
        )
        self.TruncateFromTime = channel.unary_unary(
            "/ragzoom.rpc.IndexerService/TruncateFromTime",
            request_serializer=dynamic__summary__pb2.TruncateFromTimeRequest.SerializeToString,
            response_deserializer=dynamic__summary__pb2.TruncateFromTimeResponse.FromString,
            _registered_method=True,
        )


class IndexerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IndexDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AppendText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def BatchAppendText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def TruncateDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def TruncateFromTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_IndexerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "IndexDocument": grpc.unary_unary_rpc_method_handler(
            servicer.IndexDocument,
            request_deserializer=dynamic__summary__pb2.IndexDocumentRequest.FromString,
            response_serializer=dynamic__summary__pb2.IndexDocumentResponse.SerializeToString,
        ),
        "AppendText": grpc.unary_unary_rpc_method_handler(
            servicer.AppendText,
            request_deserializer=dynamic__summary__pb2.AppendTextRequest.FromString,
            response_serializer=dynamic__summary__pb2.AppendTextResponse.SerializeToString,
        ),
        "BatchAppendText": grpc.unary_unary_rpc_method_handler(
            servicer.BatchAppendText,
            request_deserializer=dynamic__summary__pb2.BatchAppendTextRequest.FromString,
            response_serializer=dynamic__summary__pb2.BatchAppendTextResponse.SerializeToString,
        ),
        "TruncateDocument": grpc.unary_unary_rpc_method_handler(
            servicer.TruncateDocument,
            request_deserializer=dynamic__summary__pb2.TruncateDocumentRequest.FromString,
            response_serializer=dynamic__summary__pb2.TruncateDocumentResponse.SerializeToString,
        ),
        "TruncateFromTime": grpc.unary_unary_rpc_method_handler(
            servicer.TruncateFromTime,
            request_deserializer=dynamic__summary__pb2.TruncateFromTimeRequest.FromString,
            response_serializer=dynamic__summary__pb2.TruncateFromTimeResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "ragzoom.rpc.IndexerService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "ragzoom.rpc.IndexerService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class IndexerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IndexDocument(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ragzoom.rpc.IndexerService/IndexDocument",
            dynamic__summary__pb2.IndexDocumentRequest.SerializeToString,
            dynamic__summary__pb2.IndexDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AppendText(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ragzoom.rpc.IndexerService/AppendText",
            dynamic__summary__pb2.AppendTextRequest.SerializeToString,
            dynamic__summary__pb2.AppendTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def BatchAppendText(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ragzoom.rpc.IndexerService/BatchAppendText",
            dynamic__summary__pb2.BatchAppendTextRequest.SerializeToString,
            dynamic__summary__pb2.BatchAppendTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def TruncateDocument(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ragzoom.rpc.IndexerService/TruncateDocument",
            dynamic__summary__pb2.TruncateDocumentRequest.SerializeToString,
            dynamic__summary__pb2.TruncateDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def TruncateFromTime(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ragzoom.rpc.IndexerService/TruncateFromTime",
            dynamic__summary__pb2.TruncateFromTimeRequest.SerializeToString,
            dynamic__summary__pb2.TruncateFromTimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class RetrievalServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Retrieve = channel.unary_unary(
            "/ragzoom.rpc.RetrievalService/Retrieve",
            request_serializer=dynamic__summary__pb2.RetrieveRequest.SerializeToString,
            response_deserializer=dynamic__summary__pb2.RetrieveResponse.FromString,
            _registered_method=True,
        )
        self.ExecuteQuery = channel.unary_unary(
            "/ragzoom.rpc.RetrievalService/ExecuteQuery",
            request_serializer=dynamic__summary__pb2.ExecuteQueryRequest.SerializeToString,
            response_deserializer=dynamic__summary__pb2.ExecuteQueryResponse.FromString,
            _registered_method=True,
        )


class RetrievalServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ExecuteQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RetrievalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Retrieve": grpc.unary_unary_rpc_method_handler(
            servicer.Retrieve,
            request_deserializer=dynamic__summary__pb2.RetrieveRequest.FromString,
            response_serializer=dynamic__summary__pb2.RetrieveResponse.SerializeToString,
        ),
        "ExecuteQuery": grpc.unary_unary_rpc_method_handler(
            servicer.ExecuteQuery,
            request_deserializer=dynamic__summary__pb2.ExecuteQueryRequest.FromString,
            response_serializer=dynamic__summary__pb2.ExecuteQueryResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "ragzoom.rpc.RetrievalService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "ragzoom.rpc.RetrievalService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class RetrievalService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Retrieve(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ragzoom.rpc.RetrievalService/Retrieve",
            dynamic__summary__pb2.RetrieveRequest.SerializeToString,
            dynamic__summary__pb2.RetrieveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ExecuteQuery(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ragzoom.rpc.RetrievalService/ExecuteQuery",
            dynamic__summary__pb2.ExecuteQueryRequest.SerializeToString,
            dynamic__summary__pb2.ExecuteQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class WorkerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunWorkers = channel.unary_stream(
            "/ragzoom.rpc.WorkerService/RunWorkers",
            request_serializer=dynamic__summary__pb2.RunWorkersRequest.SerializeToString,
            response_deserializer=dynamic__summary__pb2.RunWorkersResponse.FromString,
            _registered_method=True,
        )
        self.GetDocument = channel.unary_unary(
            "/ragzoom.rpc.WorkerService/GetDocument",
            request_serializer=dynamic__summary__pb2.GetDocumentRequest.SerializeToString,
            response_deserializer=dynamic__summary__pb2.GetDocumentResponse.FromString,
            _registered_method=True,
        )
        self.GetDocumentStatus = channel.unary_unary(
            "/ragzoom.rpc.WorkerService/GetDocumentStatus",
            request_serializer=dynamic__summary__pb2.DocumentStatusRequest.SerializeToString,
            response_deserializer=dynamic__summary__pb2.DocumentStatusResponse.FromString,
            _registered_method=True,
        )
        self.GetTelemetry = channel.unary_unary(
            "/ragzoom.rpc.WorkerService/GetTelemetry",
            request_serializer=dynamic__summary__pb2.GetTelemetryRequest.SerializeToString,
            response_deserializer=dynamic__summary__pb2.GetTelemetryResponse.FromString,
            _registered_method=True,
        )
        self.ClearDocument = channel.unary_unary(
            "/ragzoom.rpc.WorkerService/ClearDocument",
            request_serializer=dynamic__summary__pb2.ClearDocumentRequest.SerializeToString,
            response_deserializer=dynamic__summary__pb2.ClearDocumentResponse.FromString,
            _registered_method=True,
        )
        self.ExportTelemetry = channel.unary_unary(
            "/ragzoom.rpc.WorkerService/ExportTelemetry",
            request_serializer=dynamic__summary__pb2.ExportTelemetryRequest.SerializeToString,
            response_deserializer=dynamic__summary__pb2.ExportTelemetryResponse.FromString,
            _registered_method=True,
        )
        self.ListDocuments = channel.unary_unary(
            "/ragzoom.rpc.WorkerService/ListDocuments",
            request_serializer=dynamic__summary__pb2.ListDocumentsRequest.SerializeToString,
            response_deserializer=dynamic__summary__pb2.ListDocumentsResponse.FromString,
            _registered_method=True,
        )
        self.GetSystemStatus = channel.unary_unary(
            "/ragzoom.rpc.WorkerService/GetSystemStatus",
            request_serializer=dynamic__summary__pb2.GetSystemStatusRequest.SerializeToString,
            response_deserializer=dynamic__summary__pb2.GetSystemStatusResponse.FromString,
            _registered_method=True,
        )
        self.GetCostStats = channel.unary_unary(
            "/ragzoom.rpc.WorkerService/GetCostStats",
            request_serializer=dynamic__summary__pb2.GetCostStatsRequest.SerializeToString,
            response_deserializer=dynamic__summary__pb2.GetCostStatsResponse.FromString,
            _registered_method=True,
        )


class WorkerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunWorkers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetDocumentStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetTelemetry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ClearDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ExportTelemetry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetSystemStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetCostStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "RunWorkers": grpc.unary_stream_rpc_method_handler(
            servicer.RunWorkers,
            request_deserializer=dynamic__summary__pb2.RunWorkersRequest.FromString,
            response_serializer=dynamic__summary__pb2.RunWorkersResponse.SerializeToString,
        ),
        "GetDocument": grpc.unary_unary_rpc_method_handler(
            servicer.GetDocument,
            request_deserializer=dynamic__summary__pb2.GetDocumentRequest.FromString,
            response_serializer=dynamic__summary__pb2.GetDocumentResponse.SerializeToString,
        ),
        "GetDocumentStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetDocumentStatus,
            request_deserializer=dynamic__summary__pb2.DocumentStatusRequest.FromString,
            response_serializer=dynamic__summary__pb2.DocumentStatusResponse.SerializeToString,
        ),
        "GetTelemetry": grpc.unary_unary_rpc_method_handler(
            servicer.GetTelemetry,
            request_deserializer=dynamic__summary__pb2.GetTelemetryRequest.FromString,
            response_serializer=dynamic__summary__pb2.GetTelemetryResponse.SerializeToString,
        ),
        "ClearDocument": grpc.unary_unary_rpc_method_handler(
            servicer.ClearDocument,
            request_deserializer=dynamic__summary__pb2.ClearDocumentRequest.FromString,
            response_serializer=dynamic__summary__pb2.ClearDocumentResponse.SerializeToString,
        ),
        "ExportTelemetry": grpc.unary_unary_rpc_method_handler(
            servicer.ExportTelemetry,
            request_deserializer=dynamic__summary__pb2.ExportTelemetryRequest.FromString,
            response_serializer=dynamic__summary__pb2.ExportTelemetryResponse.SerializeToString,
        ),
        "ListDocuments": grpc.unary_unary_rpc_method_handler(
            servicer.ListDocuments,
            request_deserializer=dynamic__summary__pb2.ListDocumentsRequest.FromString,
            response_serializer=dynamic__summary__pb2.ListDocumentsResponse.SerializeToString,
        ),
        "GetSystemStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetSystemStatus,
            request_deserializer=dynamic__summary__pb2.GetSystemStatusRequest.FromString,
            response_serializer=dynamic__summary__pb2.GetSystemStatusResponse.SerializeToString,
        ),
        "GetCostStats": grpc.unary_unary_rpc_method_handler(
            servicer.GetCostStats,
            request_deserializer=dynamic__summary__pb2.GetCostStatsRequest.FromString,
            response_serializer=dynamic__summary__pb2.GetCostStatsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "ragzoom.rpc.WorkerService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "ragzoom.rpc.WorkerService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class WorkerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunWorkers(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/ragzoom.rpc.WorkerService/RunWorkers",
            dynamic__summary__pb2.RunWorkersRequest.SerializeToString,
            dynamic__summary__pb2.RunWorkersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetDocument(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ragzoom.rpc.WorkerService/GetDocument",
            dynamic__summary__pb2.GetDocumentRequest.SerializeToString,
            dynamic__summary__pb2.GetDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetDocumentStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ragzoom.rpc.WorkerService/GetDocumentStatus",
            dynamic__summary__pb2.DocumentStatusRequest.SerializeToString,
            dynamic__summary__pb2.DocumentStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetTelemetry(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ragzoom.rpc.WorkerService/GetTelemetry",
            dynamic__summary__pb2.GetTelemetryRequest.SerializeToString,
            dynamic__summary__pb2.GetTelemetryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ClearDocument(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ragzoom.rpc.WorkerService/ClearDocument",
            dynamic__summary__pb2.ClearDocumentRequest.SerializeToString,
            dynamic__summary__pb2.ClearDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ExportTelemetry(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ragzoom.rpc.WorkerService/ExportTelemetry",
            dynamic__summary__pb2.ExportTelemetryRequest.SerializeToString,
            dynamic__summary__pb2.ExportTelemetryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListDocuments(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ragzoom.rpc.WorkerService/ListDocuments",
            dynamic__summary__pb2.ListDocumentsRequest.SerializeToString,
            dynamic__summary__pb2.ListDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetSystemStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ragzoom.rpc.WorkerService/GetSystemStatus",
            dynamic__summary__pb2.GetSystemStatusRequest.SerializeToString,
            dynamic__summary__pb2.GetSystemStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetCostStats(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ragzoom.rpc.WorkerService/GetCostStats",
            dynamic__summary__pb2.GetCostStatsRequest.SerializeToString,
            dynamic__summary__pb2.GetCostStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class SessionIngestionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSessionCursor = channel.unary_unary(
            "/ragzoom.rpc.SessionIngestionService/GetSessionCursor",
            request_serializer=dynamic__summary__pb2.GetSessionCursorRequest.SerializeToString,
            response_deserializer=dynamic__summary__pb2.GetSessionCursorResponse.FromString,
            _registered_method=True,
        )
        self.IngestSession = channel.unary_unary(
            "/ragzoom.rpc.SessionIngestionService/IngestSession",
            request_serializer=dynamic__summary__pb2.IngestSessionRequest.SerializeToString,
            response_deserializer=dynamic__summary__pb2.IngestSessionResponse.FromString,
            _registered_method=True,
        )
        self.GetCompactionBoundary = channel.unary_unary(
            "/ragzoom.rpc.SessionIngestionService/GetCompactionBoundary",
            request_serializer=dynamic__summary__pb2.GetCompactionBoundaryRequest.SerializeToString,
            response_deserializer=dynamic__summary__pb2.GetCompactionBoundaryResponse.FromString,
            _registered_method=True,
        )
        self.ResetSessionCursor = channel.unary_unary(
            "/ragzoom.rpc.SessionIngestionService/ResetSessionCursor",
            request_serializer=dynamic__summary__pb2.ResetSessionCursorRequest.SerializeToString,
            response_deserializer=dynamic__summary__pb2.ResetSessionCursorResponse.FromString,
            _registered_method=True,
        )


class SessionIngestionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSessionCursor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def IngestSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetCompactionBoundary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ResetSessionCursor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SessionIngestionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetSessionCursor": grpc.unary_unary_rpc_method_handler(
            servicer.GetSessionCursor,
            request_deserializer=dynamic__summary__pb2.GetSessionCursorRequest.FromString,
            response_serializer=dynamic__summary__pb2.GetSessionCursorResponse.SerializeToString,
        ),
        "IngestSession": grpc.unary_unary_rpc_method_handler(
            servicer.IngestSession,
            request_deserializer=dynamic__summary__pb2.IngestSessionRequest.FromString,
            response_serializer=dynamic__summary__pb2.IngestSessionResponse.SerializeToString,
        ),
        "GetCompactionBoundary": grpc.unary_unary_rpc_method_handler(
            servicer.GetCompactionBoundary,
            request_deserializer=dynamic__summary__pb2.GetCompactionBoundaryRequest.FromString,
            response_serializer=dynamic__summary__pb2.GetCompactionBoundaryResponse.SerializeToString,
        ),
        "ResetSessionCursor": grpc.unary_unary_rpc_method_handler(
            servicer.ResetSessionCursor,
            request_deserializer=dynamic__summary__pb2.ResetSessionCursorRequest.FromString,
            response_serializer=dynamic__summary__pb2.ResetSessionCursorResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "ragzoom.rpc.SessionIngestionService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "ragzoom.rpc.SessionIngestionService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class SessionIngestionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSessionCursor(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ragzoom.rpc.SessionIngestionService/GetSessionCursor",
            dynamic__summary__pb2.GetSessionCursorRequest.SerializeToString,
            dynamic__summary__pb2.GetSessionCursorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def IngestSession(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ragzoom.rpc.SessionIngestionService/IngestSession",
            dynamic__summary__pb2.IngestSessionRequest.SerializeToString,
            dynamic__summary__pb2.IngestSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetCompactionBoundary(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ragzoom.rpc.SessionIngestionService/GetCompactionBoundary",
            dynamic__summary__pb2.GetCompactionBoundaryRequest.SerializeToString,
            dynamic__summary__pb2.GetCompactionBoundaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ResetSessionCursor(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ragzoom.rpc.SessionIngestionService/ResetSessionCursor",
            dynamic__summary__pb2.ResetSessionCursorRequest.SerializeToString,
            dynamic__summary__pb2.ResetSessionCursorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class SearchServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
            "/ragzoom.rpc.SearchService/Search",
            request_serializer=dynamic__summary__pb2.SearchRequest.SerializeToString,
            response_deserializer=dynamic__summary__pb2.SearchResponse.FromString,
            _registered_method=True,
        )


class SearchServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SearchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Search": grpc.unary_unary_rpc_method_handler(
            servicer.Search,
            request_deserializer=dynamic__summary__pb2.SearchRequest.FromString,
            response_serializer=dynamic__summary__pb2.SearchResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "ragzoom.rpc.SearchService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "ragzoom.rpc.SearchService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class SearchService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Search(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ragzoom.rpc.SearchService/Search",
            dynamic__summary__pb2.SearchRequest.SerializeToString,
            dynamic__summary__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


# jscpd:ignore-end
