"""Tests for transcript formatting and compaction segment batching."""

from __future__ import annotations

import json
from pathlib import Path

from memory_service.ingestion.claude.transcript_sync import (
    SessionState,
    execute_sync,
)
from tests.conftest import FakeTranscriptClient


class TestTranscriptFormatting:
    """Tests for transcript formatting issues."""

    def test_double_newlines_between_messages(self, tmp_path: Path) -> None:
        """Messages should be separated by double newlines within a turn."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        transcript_path.write_text(
            "\n".join(
                [
                    json.dumps(
                        {
                            "uuid": "msg1",
                            "parentUuid": None,
                            "type": "user",
                            "message": {"content": "First message"},
                        }
                    ),
                    json.dumps(
                        {
                            "uuid": "msg2",
                            "parentUuid": "msg1",
                            "type": "assistant",
                            "message": {
                                "content": [{"type": "text", "text": "Response"}]
                            },
                        }
                    ),
                    json.dumps(
                        {
                            "uuid": "msg3",
                            "parentUuid": "msg2",
                            "type": "user",
                            "message": {"content": "Second message"},
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        # With turn-based batching: turn 1 = msg1+msg2, turn 2 = msg3
        assert len(client.appends) == 2

        # First turn should have user and assistant with double newlines between
        first_turn = client.appends[0][1]
        assert first_turn.startswith("[USER]")
        assert "\n\n[ASSISTANT]" in first_turn

        # Check formatting within first turn
        lines = first_turn.split("\n")
        for i, line in enumerate(lines):
            if line.startswith("[USER]") or line.startswith("[ASSISTANT]"):
                # Either it's the first line, or preceded by empty line
                if i > 0:
                    assert lines[i - 1] == "", f"Missing blank line before {line}"

        # Second turn should be just the user message
        second_turn = client.appends[1][1]
        assert "[USER]" in second_turn
        assert "Second message" in second_turn

    def test_slash_commands_simplified(self, tmp_path: Path) -> None:
        """Slash commands should be simplified from XML format."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        # The XML command format that Claude Code produces
        command_content = (
            "Caveat: The messages below were generated by the user while running "
            "local commands. DO NOT respond to these messages or otherwise consider "
            "them in your response unless the user explicitly asks you to."
            "<command-name>/clear</command-name>"
            "<command-message>clear</command-message>"
            "<command-args></command-args>"
        )

        transcript_path.write_text(
            json.dumps(
                {
                    "uuid": "msg1",
                    "parentUuid": None,
                    "type": "user",
                    "message": {"content": command_content},
                }
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        assert len(client.appends) == 1
        text = client.appends[0][1]

        # Should NOT contain the verbose XML
        assert "<command-name>" not in text
        assert "<command-message>" not in text
        assert "<command-args>" not in text
        assert "Caveat:" not in text

        # Should contain the simplified command
        assert "/clear" in text

    def test_local_stdout_removed(self, tmp_path: Path) -> None:
        """Empty local-command-stdout tags should be removed."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        transcript_path.write_text(
            json.dumps(
                {
                    "uuid": "msg1",
                    "parentUuid": None,
                    "type": "user",
                    "message": {
                        "content": "<local-command-stdout></local-command-stdout>"
                    },
                }
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        # Empty messages should result in no append
        # or if appended, should not contain the tag
        if client.appends:
            text = client.appends[0][1]
            assert "<local-command-stdout>" not in text


class TestTurnBasedBatching:
    """Tests for batching at turn boundaries.

    A turn = user message(s) + subsequent assistant/tool messages.
    Each turn becomes a separate append with forced split boundaries.
    """

    def test_one_append_per_turn(self, tmp_path: Path) -> None:
        """Each turn should be a separate append."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        transcript_path.write_text(
            "\n".join(
                [
                    # Turn 1: user + assistant
                    json.dumps(
                        {
                            "uuid": "a1",
                            "parentUuid": None,
                            "type": "user",
                            "message": {"content": "Turn 1 user message"},
                        }
                    ),
                    json.dumps(
                        {
                            "uuid": "a2",
                            "parentUuid": "a1",
                            "type": "assistant",
                            "message": {
                                "content": [{"type": "text", "text": "Turn 1 reply"}]
                            },
                        }
                    ),
                    # Turn 2: user + assistant
                    json.dumps(
                        {
                            "uuid": "b1",
                            "parentUuid": "a2",
                            "type": "user",
                            "message": {"content": "Turn 2 user message"},
                        }
                    ),
                    json.dumps(
                        {
                            "uuid": "b2",
                            "parentUuid": "b1",
                            "type": "assistant",
                            "message": {
                                "content": [{"type": "text", "text": "Turn 2 reply"}]
                            },
                        }
                    ),
                    # Turn 3: user only (no assistant yet)
                    json.dumps(
                        {
                            "uuid": "c1",
                            "parentUuid": "b2",
                            "type": "user",
                            "message": {"content": "Turn 3 user message"},
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        # Should have 3 appends (one per turn)
        assert len(client.appends) == 3

        # Each append should contain its turn's content
        assert "Turn 1" in client.appends[0][1]
        assert "Turn 2" in client.appends[1][1]
        assert "Turn 3" in client.appends[2][1]

    def test_state_has_entry_per_turn(self, tmp_path: Path) -> None:
        """State should have one entry per turn for rollback."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        transcript_path.write_text(
            "\n".join(
                [
                    # Turn 1
                    json.dumps(
                        {
                            "uuid": "a1",
                            "parentUuid": None,
                            "type": "user",
                            "message": {"content": "First"},
                        }
                    ),
                    json.dumps(
                        {
                            "uuid": "a2",
                            "parentUuid": "a1",
                            "type": "assistant",
                            "message": {
                                "content": [{"type": "text", "text": "Reply 1"}]
                            },
                        }
                    ),
                    # Turn 2
                    json.dumps(
                        {
                            "uuid": "b1",
                            "parentUuid": "a2",
                            "type": "user",
                            "message": {"content": "Second"},
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        state = SessionState.load(state_path)
        assert state is not None

        # Should have 2 entries (one per turn)
        assert len(state.entries) == 2

        # First entry should be for last UUID in first turn (assistant)
        assert state.entries[0].last_uuid == "a2"

        # Second entry should be for last UUID in second turn
        assert state.entries[1].last_uuid == "b1"

    def test_turn_boundary_spans_are_correct(self, tmp_path: Path) -> None:
        """Each turn's span_end should be cumulative."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        transcript_path.write_text(
            "\n".join(
                [
                    # Turn 1
                    json.dumps(
                        {
                            "uuid": "a1",
                            "parentUuid": None,
                            "type": "user",
                            "message": {"content": "First turn content"},
                        }
                    ),
                    json.dumps(
                        {
                            "uuid": "a2",
                            "parentUuid": "a1",
                            "type": "assistant",
                            "message": {"content": [{"type": "text", "text": "Reply"}]},
                        }
                    ),
                    # Turn 2
                    json.dumps(
                        {
                            "uuid": "b1",
                            "parentUuid": "a2",
                            "type": "user",
                            "message": {"content": "Second turn content"},
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        state = SessionState.load(state_path)
        assert state is not None
        assert len(state.entries) == 2

        # First turn's span_end should be length of first append
        first_text = client.appends[0][1]
        assert state.entries[0].span_end == len(first_text)

        # Second turn's span_end should be cumulative
        second_text = client.appends[1][1]
        assert state.entries[1].span_end == len(first_text) + len(second_text)

    def test_consecutive_user_messages_same_turn(self, tmp_path: Path) -> None:
        """Consecutive user messages should stay in the same turn."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        transcript_path.write_text(
            "\n".join(
                [
                    # Turn 1: multiple user messages, then assistant
                    json.dumps(
                        {
                            "uuid": "u1",
                            "parentUuid": None,
                            "type": "user",
                            "message": {"content": "First user message"},
                        }
                    ),
                    json.dumps(
                        {
                            "uuid": "u2",
                            "parentUuid": "u1",
                            "type": "user",
                            "message": {"content": "Second user message"},
                        }
                    ),
                    json.dumps(
                        {
                            "uuid": "a1",
                            "parentUuid": "u2",
                            "type": "assistant",
                            "message": {"content": [{"type": "text", "text": "Reply"}]},
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        # All in one turn
        assert len(client.appends) == 1
        text = client.appends[0][1]
        assert "First user message" in text
        assert "Second user message" in text
        assert "Reply" in text


class TestToolUsageBatching:
    """Tests for batching consecutive tool usage messages."""

    def test_tool_only_with_text_between_not_batched(self, tmp_path: Path) -> None:
        """Tool-only messages separated by text messages should not batch."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        # This mirrors real transcript pattern: tool, result, text, tool, result
        transcript_path.write_text(
            "\n".join(
                [
                    # First tool use
                    json.dumps(
                        {
                            "uuid": "msg1",
                            "parentUuid": None,
                            "type": "assistant",
                            "message": {
                                "content": [
                                    {
                                        "type": "tool_use",
                                        "name": "Bash",
                                        "input": {"command": "git status"},
                                    },
                                ]
                            },
                        }
                    ),
                    # Tool result
                    json.dumps(
                        {
                            "uuid": "msg2",
                            "parentUuid": "msg1",
                            "type": "user",
                            "toolUseResult": "output",
                            "message": {"content": "..."},
                        }
                    ),
                    # Text response (breaks the chain)
                    json.dumps(
                        {
                            "uuid": "msg3",
                            "parentUuid": "msg2",
                            "type": "assistant",
                            "message": {
                                "content": [
                                    {"type": "text", "text": "The status shows..."},
                                ]
                            },
                        }
                    ),
                    # Second tool use
                    json.dumps(
                        {
                            "uuid": "msg4",
                            "parentUuid": "msg3",
                            "type": "assistant",
                            "message": {
                                "content": [
                                    {
                                        "type": "tool_use",
                                        "name": "Read",
                                        "input": {"file_path": "README.md"},
                                    },
                                ]
                            },
                        }
                    ),
                    # Tool result
                    json.dumps(
                        {
                            "uuid": "msg5",
                            "parentUuid": "msg4",
                            "type": "user",
                            "toolUseResult": "content",
                            "message": {"content": "..."},
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        text = client.appends[0][1]

        # Should have two separate tool entries because text message broke the chain
        assert text.count("[Used 1 tool:") == 2
        assert "Bash(git status)" in text
        assert "Read(README.md)" in text
        assert "The status shows" in text

    def test_consecutive_tool_uses_batched(self, tmp_path: Path) -> None:
        """Consecutive tool-only messages should be batched into one line."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        # Simulate consecutive tool-only assistant messages
        transcript_path.write_text(
            "\n".join(
                [
                    # First tool use (tool-only, no text)
                    json.dumps(
                        {
                            "uuid": "msg1",
                            "parentUuid": None,
                            "type": "assistant",
                            "message": {
                                "content": [
                                    {
                                        "type": "tool_use",
                                        "name": "Bash",
                                        "input": {"command": "git status"},
                                    },
                                ]
                            },
                        }
                    ),
                    # Tool result (user type)
                    json.dumps(
                        {
                            "uuid": "msg2",
                            "parentUuid": "msg1",
                            "type": "user",
                            "toolUseResult": "some output",
                            "message": {"content": "..."},
                        }
                    ),
                    # Second tool use (tool-only)
                    json.dumps(
                        {
                            "uuid": "msg3",
                            "parentUuid": "msg2",
                            "type": "assistant",
                            "message": {
                                "content": [
                                    {
                                        "type": "tool_use",
                                        "name": "Read",
                                        "input": {"file_path": "README.md"},
                                    },
                                ]
                            },
                        }
                    ),
                    # Tool result
                    json.dumps(
                        {
                            "uuid": "msg4",
                            "parentUuid": "msg3",
                            "type": "user",
                            "toolUseResult": "file content",
                            "message": {"content": "..."},
                        }
                    ),
                    # Third tool use (tool-only)
                    json.dumps(
                        {
                            "uuid": "msg5",
                            "parentUuid": "msg4",
                            "type": "assistant",
                            "message": {
                                "content": [
                                    {
                                        "type": "tool_use",
                                        "name": "Grep",
                                        "input": {"pattern": "TODO"},
                                    },
                                ]
                            },
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        assert len(client.appends) == 1
        text = client.appends[0][1]

        # Should have a single batched message with all tool names
        assert "[Used 3 tools:" in text
        assert "Bash(git status)" in text
        assert "Read(README.md)" in text
        assert "Grep(TODO)" in text

        # Should NOT have multiple separate tool lines
        assert text.count("[Used") == 1

    def test_tool_names_include_summary(self, tmp_path: Path) -> None:
        """Tool names should include a brief summary of the invocation."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        transcript_path.write_text(
            "\n".join(
                [
                    json.dumps(
                        {
                            "uuid": "msg1",
                            "parentUuid": None,
                            "type": "assistant",
                            "message": {
                                "content": [
                                    {
                                        "type": "tool_use",
                                        "name": "Bash",
                                        "input": {
                                            "command": "python -m ragzoom.cli query --debug"
                                        },
                                    },
                                ]
                            },
                        }
                    ),
                    json.dumps(
                        {
                            "uuid": "msg2",
                            "parentUuid": "msg1",
                            "type": "user",
                            "toolUseResult": "output",
                            "message": {"content": "..."},
                        }
                    ),
                    json.dumps(
                        {
                            "uuid": "msg3",
                            "parentUuid": "msg2",
                            "type": "assistant",
                            "message": {
                                "content": [
                                    {
                                        "type": "tool_use",
                                        "name": "Read",
                                        "input": {"file_path": "ragzoom/db_utils.py"},
                                    },
                                ]
                            },
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        text = client.appends[0][1]

        # Should show tool with argument summary
        assert "Bash(python -m ragzoom" in text or "Bash(ragzoom" in text
        assert "Read(ragzoom/db_utils.py)" in text

    def test_single_tool_use_not_batched(self, tmp_path: Path) -> None:
        """A single tool use followed by text should not be batched."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        transcript_path.write_text(
            "\n".join(
                [
                    json.dumps(
                        {
                            "uuid": "msg1",
                            "parentUuid": None,
                            "type": "assistant",
                            "message": {
                                "content": [
                                    {"type": "text", "text": "Let me check."},
                                    {
                                        "type": "tool_use",
                                        "name": "Bash",
                                        "input": {"command": "ls"},
                                    },
                                ]
                            },
                        }
                    ),
                    json.dumps(
                        {
                            "uuid": "msg2",
                            "parentUuid": "msg1",
                            "type": "user",
                            "toolUseResult": "output",
                            "message": {"content": "..."},
                        }
                    ),
                    # Assistant responds with text (breaking the tool-only chain)
                    json.dumps(
                        {
                            "uuid": "msg3",
                            "parentUuid": "msg2",
                            "type": "assistant",
                            "message": {
                                "content": [
                                    {"type": "text", "text": "Here's what I found."},
                                ]
                            },
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        text = client.appends[0][1]

        # Should have the tool usage
        assert "[Used 1 tool: Bash(ls)]" in text

        # And the follow-up text
        assert "Here's what I found" in text


class TestCommandHandling:
    """Tests for slash command transcription."""

    def test_builtin_command_transcribed_simply(self, tmp_path: Path) -> None:
        """Built-in commands like /compact should be transcribed as [User issued /compact command]."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        transcript_path.write_text(
            "\n".join(
                [
                    # Command invocation
                    json.dumps(
                        {
                            "uuid": "cmd1",
                            "parentUuid": None,
                            "type": "user",
                            "message": {
                                "content": "<command-name>/compact</command-name>\n"
                                "<command-message>compact</command-message>\n"
                                "<command-args></command-args>"
                            },
                        }
                    ),
                    # Command output (should be skipped)
                    json.dumps(
                        {
                            "uuid": "out1",
                            "parentUuid": "cmd1",
                            "type": "user",
                            "message": {
                                "content": "<local-command-stdout>Compacted</local-command-stdout>"
                            },
                        }
                    ),
                    # Assistant response
                    json.dumps(
                        {
                            "uuid": "resp1",
                            "parentUuid": "out1",
                            "type": "assistant",
                            "message": {"content": [{"type": "text", "text": "Done."}]},
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        text = client.appends[0][1]

        # Should have the command as a simple notation
        assert "[User issued /compact command]" in text
        # Should NOT have the raw command output
        assert "Compacted" not in text
        assert "<local-command-stdout>" not in text
        # Should have the assistant response
        assert "Done." in text

    def test_custom_command_expansion_skipped(self, tmp_path: Path) -> None:
        """Custom commands like /commit should skip the expanded file content."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        transcript_path.write_text(
            "\n".join(
                [
                    # Command invocation
                    json.dumps(
                        {
                            "uuid": "cmd1",
                            "parentUuid": None,
                            "type": "user",
                            "message": {
                                "content": "<command-message>commit</command-message>\n"
                                "<command-name>/commit</command-name>"
                            },
                        }
                    ),
                    # Command expansion (the .md file content - should be skipped)
                    json.dumps(
                        {
                            "uuid": "exp1",
                            "parentUuid": "cmd1",
                            "type": "user",
                            "message": {
                                "content": [
                                    {
                                        "type": "text",
                                        "text": "# /commit\n## Context\n- Current branch: main\n"
                                        "## Task\nClean up and commit...",
                                    }
                                ]
                            },
                        }
                    ),
                    # Assistant response
                    json.dumps(
                        {
                            "uuid": "resp1",
                            "parentUuid": "exp1",
                            "type": "assistant",
                            "message": {
                                "content": [
                                    {"type": "text", "text": "Committed changes."}
                                ]
                            },
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        text = client.appends[0][1]

        # Should have the command as a simple notation
        assert "[User issued /commit command]" in text
        # Should NOT have the expanded command file content
        assert "# /commit" not in text
        assert "Current branch" not in text
        assert "Clean up and commit" not in text
        # Should have the assistant response
        assert "Committed changes." in text

    def test_command_followed_by_assistant(self, tmp_path: Path) -> None:
        """Command directly followed by assistant (no expansion) should work."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        transcript_path.write_text(
            "\n".join(
                [
                    # Command invocation
                    json.dumps(
                        {
                            "uuid": "cmd1",
                            "parentUuid": None,
                            "type": "user",
                            "message": {
                                "content": "<command-name>/clear</command-name>\n"
                                "<command-message>clear</command-message>\n"
                                "<command-args></command-args>"
                            },
                        }
                    ),
                    # Assistant responds directly (no user message in between)
                    json.dumps(
                        {
                            "uuid": "resp1",
                            "parentUuid": "cmd1",
                            "type": "assistant",
                            "message": {
                                "content": [
                                    {"type": "text", "text": "Context cleared."}
                                ]
                            },
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        text = client.appends[0][1]

        # Should have the command
        assert "[User issued /clear command]" in text
        # Should have the assistant response
        assert "Context cleared." in text

    def test_hyphenated_command_cleaned_properly(self, tmp_path: Path) -> None:
        """Commands with hyphens like /review-pr should be cleaned properly."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        transcript_path.write_text(
            "\n".join(
                [
                    # Hyphenated command invocation
                    json.dumps(
                        {
                            "uuid": "cmd1",
                            "parentUuid": None,
                            "type": "user",
                            "message": {
                                "content": "<command-name>/review-pr</command-name>\n"
                                "<command-message>review-pr</command-message>\n"
                                "<command-args></command-args>"
                            },
                        }
                    ),
                    # Assistant responds
                    json.dumps(
                        {
                            "uuid": "resp1",
                            "parentUuid": "cmd1",
                            "type": "assistant",
                            "message": {
                                "content": [{"type": "text", "text": "Reviewing PR."}]
                            },
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        text = client.appends[0][1]

        # Should have the hyphenated command
        assert "[User issued /review-pr command]" in text
        # Should NOT have any raw XML
        assert "<command-name>" not in text
        assert "<command-message>" not in text
        assert "Reviewing PR." in text

    def test_quoted_command_xml_not_transformed(self, tmp_path: Path) -> None:
        """User messages that QUOTE command XML should not be transformed.

        This tests the bug where a user message like:
        "transform this: <command-name>/clear</command-name>..."
        was being incorrectly transformed to "[User issued /clear command]"
        instead of preserving the user's actual message content.
        """
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        # User message that quotes/discusses command XML (not an actual command)
        user_message = (
            "yes, we should filter and transform things like this:\n\n"
            "[USER]\n"
            "<command-name>/clear</command-name>\n"
            "<command-message>clear</command-message>\n"
            "<command-args></command-args>\n\n"
            "to simply:\n\n"
            "[USER]\n"
            "/clear"
        )

        transcript_path.write_text(
            "\n".join(
                [
                    json.dumps(
                        {
                            "uuid": "msg1",
                            "parentUuid": None,
                            "type": "user",
                            "message": {"content": user_message},
                        }
                    ),
                    json.dumps(
                        {
                            "uuid": "msg2",
                            "parentUuid": "msg1",
                            "type": "assistant",
                            "message": {
                                "content": [
                                    {"type": "text", "text": "I'll update the code."}
                                ]
                            },
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        text = client.appends[0][1]

        # Should NOT be transformed to "[User issued /clear command]"
        # because the user is discussing/quoting commands, not issuing one
        assert "[User issued /clear command]" not in text

        # Should preserve the user's actual message content
        assert "we should filter and transform" in text
        assert "to simply:" in text

    def test_message_starting_with_command_xml_is_transformed(
        self, tmp_path: Path
    ) -> None:
        """Messages that ARE commands (start with command XML) should be transformed."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        # Actual command message (starts with command XML)
        command_message = (
            "<command-name>/clear</command-name>\n"
            "<command-message>clear</command-message>\n"
            "<command-args></command-args>"
        )

        transcript_path.write_text(
            json.dumps(
                {
                    "uuid": "msg1",
                    "parentUuid": None,
                    "type": "user",
                    "message": {"content": command_message},
                }
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        text = client.appends[0][1]

        # This IS a command, so it SHOULD be transformed
        assert "/clear" in text
        # Raw XML should be removed
        assert "<command-name>" not in text

    def test_command_with_caveat_prefix_is_transformed(self, tmp_path: Path) -> None:
        """Commands preceded by caveat boilerplate should still be transformed."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        # Command with caveat prefix (common pattern from Claude Code)
        command_message = (
            "Caveat: The messages below were generated by the user while running "
            "local commands. DO NOT respond to these messages or otherwise consider "
            "them in your response unless the user explicitly asks you to.\n"
            "<command-name>/clear</command-name>\n"
            "<command-message>clear</command-message>\n"
            "<command-args></command-args>"
        )

        transcript_path.write_text(
            json.dumps(
                {
                    "uuid": "msg1",
                    "parentUuid": None,
                    "type": "user",
                    "message": {"content": command_message},
                }
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        text = client.appends[0][1]

        # This IS a command (caveat + command XML), so it SHOULD be transformed
        assert "/clear" in text
        # Raw XML and caveat should be removed
        assert "<command-name>" not in text
        assert "Caveat:" not in text

    def test_quoted_local_command_stdout_preserved(self, tmp_path: Path) -> None:
        """Quoted <local-command-stdout> tags should not be stripped from user messages.

        When a user discusses or quotes the command format, local-command-stdout
        tags are part of their content and should be preserved, not stripped.
        """
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        # User message that quotes command format including stdout tags
        user_message = (
            "Here's what the command output looks like:\n\n"
            "<local-command-stdout>some output</local-command-stdout>\n\n"
            "We should handle this properly."
        )

        transcript_path.write_text(
            json.dumps(
                {
                    "uuid": "msg1",
                    "parentUuid": None,
                    "type": "user",
                    "message": {"content": user_message},
                }
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        text = client.appends[0][1]

        # The quoted local-command-stdout should be preserved
        assert "<local-command-stdout>" in text
        assert "some output" in text
        assert "We should handle this properly" in text

    def test_quoted_caveat_in_middle_of_message_preserved(self, tmp_path: Path) -> None:
        """Caveat text quoted in the middle of a message should be preserved.

        The caveat boilerplate should only be stripped when it appears at the
        START of a command message, not when quoted as part of a discussion.
        """
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        # User message that quotes caveat in the middle
        user_message = (
            "The system adds this boilerplate:\n\n"
            "Caveat: The messages below were generated by the user while running "
            "local commands. DO NOT respond to these messages or otherwise consider "
            "them in your response unless the user explicitly asks you to.\n\n"
            "We should filter it out."
        )

        transcript_path.write_text(
            json.dumps(
                {
                    "uuid": "msg1",
                    "parentUuid": None,
                    "type": "user",
                    "message": {"content": user_message},
                }
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        text = client.appends[0][1]

        # Caveat in middle of message should be preserved (it's quoted content)
        assert "Caveat:" in text
        assert "The system adds this boilerplate" in text
        assert "We should filter it out" in text

    def test_full_quoted_command_format_preserved(self, tmp_path: Path) -> None:
        """Full quoted command format (caveat + command + stdout) should be preserved.

        Regression test for the case where a user quotes the entire command message
        format to discuss how it should be transformed.
        """
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        # User message that quotes the full command format
        user_message = (
            "yes, we should filter and transform things like this:\n\n"
            "[USER]\n"
            "Caveat: The messages below were generated by the user while running "
            "local commands. DO NOT respond to these messages or otherwise consider "
            "them in your response unless the user explicitly asks you to.\n\n"
            "[USER]\n"
            "<command-name>/clear</command-name>\n"
            "<command-message>clear</command-message>\n"
            "<command-args></command-args>\n\n"
            "[USER]\n"
            "<local-command-stdout></local-command-stdout>\n\n"
            "to simply:\n\n"
            "[USER]\n"
            "/clear"
        )

        transcript_path.write_text(
            json.dumps(
                {
                    "uuid": "msg1",
                    "parentUuid": None,
                    "type": "user",
                    "message": {"content": user_message},
                }
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        text = client.appends[0][1]

        # All quoted content should be preserved
        assert "we should filter and transform" in text
        assert "Caveat:" in text  # Quoted caveat preserved
        assert "<command-name>/clear</command-name>" in text  # Quoted XML preserved
        assert "<local-command-stdout>" in text  # Quoted stdout tags preserved
        assert "to simply:" in text

    def test_command_with_stdout_transformed(self, tmp_path: Path) -> None:
        """Actual command messages with stdout should be transformed to just command."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        # Actual command with caveat and stdout (system-generated format)
        command_message = (
            "Caveat: The messages below were generated by the user while running "
            "local commands. DO NOT respond to these messages or otherwise consider "
            "them in your response unless the user explicitly asks you to.\n"
            "<command-name>/bash</command-name>\n"
            "<command-message>echo hello</command-message>\n"
            "<command-args></command-args>\n"
            "<local-command-stdout>hello</local-command-stdout>"
        )

        transcript_path.write_text(
            json.dumps(
                {
                    "uuid": "msg1",
                    "parentUuid": None,
                    "type": "user",
                    "message": {"content": command_message},
                }
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        text = client.appends[0][1]

        # Should be transformed to just the command
        assert "/bash" in text
        # System boilerplate should be removed
        assert "Caveat:" not in text
        assert "<command-name>" not in text
        assert "<local-command-stdout>" not in text
