"""Tests for transcript formatting and compaction segment batching."""

from __future__ import annotations

import json
from pathlib import Path

from ragzoom.claude_memory.transcript_sync import (
    SessionState,
    execute_sync,
)
from tests.conftest import FakeTranscriptClient


class TestTranscriptFormatting:
    """Tests for transcript formatting issues."""

    def test_double_newlines_between_messages(self, tmp_path: Path) -> None:
        """Messages should be separated by double newlines."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        transcript_path.write_text(
            "\n".join(
                [
                    json.dumps(
                        {
                            "uuid": "msg1",
                            "parentUuid": None,
                            "type": "user",
                            "timestamp": "2024-01-21T14:30:00Z",
                            "message": {"content": "First message"},
                        }
                    ),
                    json.dumps(
                        {
                            "uuid": "msg2",
                            "parentUuid": "msg1",
                            "type": "assistant",
                            "timestamp": "2024-01-21T14:30:05Z",
                            "message": {
                                "content": [{"type": "text", "text": "Response"}]
                            },
                        }
                    ),
                    json.dumps(
                        {
                            "uuid": "msg3",
                            "parentUuid": "msg2",
                            "type": "user",
                            "timestamp": "2024-01-21T14:30:10Z",
                            "message": {"content": "Second message"},
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        # With turn-based grouping: Turn 1 = msg1+msg2, Turn 2 = msg3 (standalone)
        assert len(client.appends) == 2

        # First turn should have user + assistant
        turn1_text = client.appends[0][1]
        assert turn1_text.startswith("[USER]")
        assert "\n\n[ASSISTANT]" in turn1_text

        # Should NOT have single newline followed by [USER]/[ASSISTANT]
        # (i.e., messages should not be run together)
        for text in [client.appends[0][1], client.appends[1][1]]:
            lines = text.split("\n")
            for i, line in enumerate(lines):
                if line.startswith("[USER]") or line.startswith("[ASSISTANT]"):
                    # Either it's the first line, or preceded by empty line
                    if i > 0:
                        assert lines[i - 1] == "", f"Missing blank line before {line}"

    def test_slash_commands_simplified(self, tmp_path: Path) -> None:
        """Slash commands should be simplified from XML format."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        # The XML command format that Claude Code produces
        command_content = (
            "Caveat: The messages below were generated by the user while running "
            "local commands. DO NOT respond to these messages or otherwise consider "
            "them in your response unless the user explicitly asks you to."
            "<command-name>/clear</command-name>"
            "<command-message>clear</command-message>"
            "<command-args></command-args>"
        )

        transcript_path.write_text(
            json.dumps(
                {
                    "uuid": "msg1",
                    "parentUuid": None,
                    "type": "user",
                    "timestamp": "2024-01-21T14:30:00Z",
                    "message": {"content": command_content},
                }
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        assert len(client.appends) == 1
        text = client.appends[0][1]

        # Should NOT contain the verbose XML
        assert "<command-name>" not in text
        assert "<command-message>" not in text
        assert "<command-args>" not in text
        assert "Caveat:" not in text

        # Should contain the simplified command
        assert "/clear" in text

    def test_local_stdout_removed(self, tmp_path: Path) -> None:
        """Empty local-command-stdout tags should be removed."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        transcript_path.write_text(
            json.dumps(
                {
                    "uuid": "msg1",
                    "parentUuid": None,
                    "type": "user",
                    "timestamp": "2024-01-21T14:30:00Z",
                    "message": {
                        "content": "<local-command-stdout></local-command-stdout>"
                    },
                }
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        # Empty messages should result in no append
        # or if appended, should not contain the tag
        if client.appends:
            text = client.appends[0][1]
            assert "<local-command-stdout>" not in text


class TestTurnBasedBatching:
    """Tests for turn-based batching (one AppendUnit per conversation turn)."""

    def test_one_append_per_turn(self, tmp_path: Path) -> None:
        """Each conversation turn should be a separate AppendUnit."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        transcript_path.write_text(
            "\n".join(
                [
                    # Turn 1: user + assistant
                    json.dumps(
                        {
                            "uuid": "a1",
                            "parentUuid": None,
                            "type": "user",
                            "timestamp": "2024-01-21T14:30:00Z",
                            "message": {"content": "Turn 1 question"},
                        }
                    ),
                    json.dumps(
                        {
                            "uuid": "a2",
                            "parentUuid": "a1",
                            "type": "assistant",
                            "timestamp": "2024-01-21T14:30:05Z",
                            "message": {
                                "content": [{"type": "text", "text": "Turn 1 reply"}]
                            },
                        }
                    ),
                    # Turn 2: user + assistant
                    json.dumps(
                        {
                            "uuid": "b1",
                            "parentUuid": "a2",
                            "type": "user",
                            "timestamp": "2024-01-21T14:30:10Z",
                            "message": {"content": "Turn 2 question"},
                        }
                    ),
                    json.dumps(
                        {
                            "uuid": "b2",
                            "parentUuid": "b1",
                            "type": "assistant",
                            "timestamp": "2024-01-21T14:30:15Z",
                            "message": {
                                "content": [{"type": "text", "text": "Turn 2 reply"}]
                            },
                        }
                    ),
                    # Turn 3: standalone user message
                    json.dumps(
                        {
                            "uuid": "c1",
                            "parentUuid": "b2",
                            "type": "user",
                            "timestamp": "2024-01-21T14:30:20Z",
                            "message": {"content": "Turn 3 question"},
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        # Should have 3 appends (one per turn)
        assert len(client.appends) == 3

        # First append should contain turn 1 content
        assert "Turn 1" in client.appends[0][1]

        # Second append should contain turn 2 content
        assert "Turn 2" in client.appends[1][1]

        # Third append should contain turn 3 content
        assert "Turn 3" in client.appends[2][1]

    def test_state_has_one_entry_per_turn(self, tmp_path: Path) -> None:
        """State should have one entry per turn for turn-level tracking.

        Per timestamped-transcript-sync.md § AppendEntry Tracking:
        "Each turn's AppendEntry.last_uuid = the last message UUID in that turn."
        """
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        transcript_path.write_text(
            "\n".join(
                [
                    # Turn 1
                    json.dumps(
                        {
                            "uuid": "a1",
                            "parentUuid": None,
                            "type": "user",
                            "timestamp": "2024-01-21T14:30:00Z",
                            "message": {"content": "First"},
                        }
                    ),
                    # Turn 2
                    json.dumps(
                        {
                            "uuid": "b1",
                            "parentUuid": "a1",
                            "type": "user",
                            "timestamp": "2024-01-21T14:30:05Z",
                            "message": {"content": "Second"},
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        state = SessionState.load(state_path)
        assert state is not None

        # Should have 2 entries (one per turn)
        assert len(state.entries) == 2

        # Each entry should be for its turn's last UUID
        assert state.entries[0].last_uuid == "a1"
        assert state.entries[1].last_uuid == "b1"

    def test_turn_spans_are_cumulative(self, tmp_path: Path) -> None:
        """Each turn's span_end should be cumulative up to that turn."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        transcript_path.write_text(
            "\n".join(
                [
                    # Turn 1
                    json.dumps(
                        {
                            "uuid": "a1",
                            "parentUuid": None,
                            "type": "user",
                            "timestamp": "2024-01-21T14:30:00Z",
                            "message": {"content": "First turn content"},
                        }
                    ),
                    # Turn 2
                    json.dumps(
                        {
                            "uuid": "b1",
                            "parentUuid": "a1",
                            "type": "user",
                            "timestamp": "2024-01-21T14:30:05Z",
                            "message": {"content": "Second turn content"},
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        state = SessionState.load(state_path)
        assert state is not None
        assert len(state.entries) == 2

        # First entry's span_end should be the length of turn 1 text
        first_turn_len = len(client.appends[0][1])
        assert state.entries[0].span_end == first_turn_len

        # Second entry's span_end should be cumulative of all turn texts
        total_len = sum(len(text) for _, text in client.appends)
        assert state.entries[1].span_end == total_len


class TestToolUsageBatching:
    """Tests for batching consecutive tool usage messages."""

    def test_tool_only_with_text_between_not_batched(self, tmp_path: Path) -> None:
        """Tool-only messages separated by text messages should not batch."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        # Turns must start with a user message
        transcript_path.write_text(
            "\n".join(
                [
                    # User prompt starts the turn
                    json.dumps(
                        {
                            "uuid": "user1",
                            "parentUuid": None,
                            "type": "user",
                            "timestamp": "2024-01-21T14:29:55Z",
                            "message": {
                                "content": "Check git status and read the readme"
                            },
                        }
                    ),
                    # First tool use
                    json.dumps(
                        {
                            "uuid": "msg1",
                            "parentUuid": "user1",
                            "type": "assistant",
                            "timestamp": "2024-01-21T14:30:00Z",
                            "message": {
                                "content": [
                                    {
                                        "type": "tool_use",
                                        "name": "Bash",
                                        "input": {"command": "git status"},
                                    },
                                ]
                            },
                        }
                    ),
                    # Tool result
                    json.dumps(
                        {
                            "uuid": "msg2",
                            "parentUuid": "msg1",
                            "type": "user",
                            "timestamp": "2024-01-21T14:30:05Z",
                            "toolUseResult": "output",
                            "message": {"content": "..."},
                        }
                    ),
                    # Text response (breaks the chain)
                    json.dumps(
                        {
                            "uuid": "msg3",
                            "parentUuid": "msg2",
                            "type": "assistant",
                            "timestamp": "2024-01-21T14:30:10Z",
                            "message": {
                                "content": [
                                    {"type": "text", "text": "The status shows..."},
                                ]
                            },
                        }
                    ),
                    # Second tool use
                    json.dumps(
                        {
                            "uuid": "msg4",
                            "parentUuid": "msg3",
                            "type": "assistant",
                            "timestamp": "2024-01-21T14:30:15Z",
                            "message": {
                                "content": [
                                    {
                                        "type": "tool_use",
                                        "name": "Read",
                                        "input": {"file_path": "README.md"},
                                    },
                                ]
                            },
                        }
                    ),
                    # Tool result
                    json.dumps(
                        {
                            "uuid": "msg5",
                            "parentUuid": "msg4",
                            "type": "user",
                            "timestamp": "2024-01-21T14:30:20Z",
                            "toolUseResult": "content",
                            "message": {"content": "..."},
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        text = client.appends[0][1]

        # Should have two separate tool entries because text message broke the chain
        assert text.count("[Used 1 tool:") == 2
        assert "Bash(git status)" in text
        assert "Read(README.md)" in text
        assert "The status shows" in text

    def test_consecutive_tool_uses_batched(self, tmp_path: Path) -> None:
        """Consecutive tool-only messages should be batched into one line."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        # Turns must start with a user message
        transcript_path.write_text(
            "\n".join(
                [
                    # User prompt starts the turn
                    json.dumps(
                        {
                            "uuid": "user1",
                            "parentUuid": None,
                            "type": "user",
                            "timestamp": "2024-01-21T14:29:55Z",
                            "message": {"content": "Search the codebase"},
                        }
                    ),
                    # First tool use (tool-only, no text)
                    json.dumps(
                        {
                            "uuid": "msg1",
                            "parentUuid": "user1",
                            "type": "assistant",
                            "timestamp": "2024-01-21T14:30:00Z",
                            "message": {
                                "content": [
                                    {
                                        "type": "tool_use",
                                        "name": "Bash",
                                        "input": {"command": "git status"},
                                    },
                                ]
                            },
                        }
                    ),
                    # Tool result (user type)
                    json.dumps(
                        {
                            "uuid": "msg2",
                            "parentUuid": "msg1",
                            "type": "user",
                            "timestamp": "2024-01-21T14:30:05Z",
                            "toolUseResult": "some output",
                            "message": {"content": "..."},
                        }
                    ),
                    # Second tool use (tool-only)
                    json.dumps(
                        {
                            "uuid": "msg3",
                            "parentUuid": "msg2",
                            "type": "assistant",
                            "timestamp": "2024-01-21T14:30:10Z",
                            "message": {
                                "content": [
                                    {
                                        "type": "tool_use",
                                        "name": "Read",
                                        "input": {"file_path": "README.md"},
                                    },
                                ]
                            },
                        }
                    ),
                    # Tool result
                    json.dumps(
                        {
                            "uuid": "msg4",
                            "parentUuid": "msg3",
                            "type": "user",
                            "timestamp": "2024-01-21T14:30:15Z",
                            "toolUseResult": "file content",
                            "message": {"content": "..."},
                        }
                    ),
                    # Third tool use (tool-only)
                    json.dumps(
                        {
                            "uuid": "msg5",
                            "parentUuid": "msg4",
                            "type": "assistant",
                            "timestamp": "2024-01-21T14:30:20Z",
                            "message": {
                                "content": [
                                    {
                                        "type": "tool_use",
                                        "name": "Grep",
                                        "input": {"pattern": "TODO"},
                                    },
                                ]
                            },
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        assert len(client.appends) == 1
        text = client.appends[0][1]

        # Should have a single batched message with all tool names
        assert "[Used 3 tools:" in text
        assert "Bash(git status)" in text
        assert "Read(README.md)" in text
        assert "Grep(TODO)" in text

        # Should NOT have multiple separate tool lines
        assert text.count("[Used") == 1

    def test_tool_names_include_summary(self, tmp_path: Path) -> None:
        """Tool names should include a brief summary of the invocation."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        transcript_path.write_text(
            "\n".join(
                [
                    # User prompt starts the turn
                    json.dumps(
                        {
                            "uuid": "user1",
                            "parentUuid": None,
                            "type": "user",
                            "timestamp": "2024-01-21T14:29:55Z",
                            "message": {"content": "Run the query"},
                        }
                    ),
                    json.dumps(
                        {
                            "uuid": "msg1",
                            "parentUuid": "user1",
                            "type": "assistant",
                            "timestamp": "2024-01-21T14:30:00Z",
                            "message": {
                                "content": [
                                    {
                                        "type": "tool_use",
                                        "name": "Bash",
                                        "input": {
                                            "command": "python -m ragzoom.cli query --debug"
                                        },
                                    },
                                ]
                            },
                        }
                    ),
                    json.dumps(
                        {
                            "uuid": "msg2",
                            "parentUuid": "msg1",
                            "type": "user",
                            "timestamp": "2024-01-21T14:30:05Z",
                            "toolUseResult": "output",
                            "message": {"content": "..."},
                        }
                    ),
                    json.dumps(
                        {
                            "uuid": "msg3",
                            "parentUuid": "msg2",
                            "type": "assistant",
                            "timestamp": "2024-01-21T14:30:10Z",
                            "message": {
                                "content": [
                                    {
                                        "type": "tool_use",
                                        "name": "Read",
                                        "input": {"file_path": "ragzoom/db_utils.py"},
                                    },
                                ]
                            },
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        text = client.appends[0][1]

        # Should show tool with argument summary
        assert "Bash(python -m ragzoom" in text or "Bash(ragzoom" in text
        assert "Read(ragzoom/db_utils.py)" in text

    def test_single_tool_use_not_batched(self, tmp_path: Path) -> None:
        """A single tool use followed by text should not be batched."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        transcript_path.write_text(
            "\n".join(
                [
                    # User prompt starts the turn
                    json.dumps(
                        {
                            "uuid": "user1",
                            "parentUuid": None,
                            "type": "user",
                            "timestamp": "2024-01-21T14:29:55Z",
                            "message": {"content": "List the files"},
                        }
                    ),
                    json.dumps(
                        {
                            "uuid": "msg1",
                            "parentUuid": "user1",
                            "type": "assistant",
                            "timestamp": "2024-01-21T14:30:00Z",
                            "message": {
                                "content": [
                                    {"type": "text", "text": "Let me check."},
                                    {
                                        "type": "tool_use",
                                        "name": "Bash",
                                        "input": {"command": "ls"},
                                    },
                                ]
                            },
                        }
                    ),
                    json.dumps(
                        {
                            "uuid": "msg2",
                            "parentUuid": "msg1",
                            "type": "user",
                            "timestamp": "2024-01-21T14:30:05Z",
                            "toolUseResult": "output",
                            "message": {"content": "..."},
                        }
                    ),
                    # Assistant responds with text (breaking the tool-only chain)
                    json.dumps(
                        {
                            "uuid": "msg3",
                            "parentUuid": "msg2",
                            "type": "assistant",
                            "timestamp": "2024-01-21T14:30:10Z",
                            "message": {
                                "content": [
                                    {"type": "text", "text": "Here's what I found."},
                                ]
                            },
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        text = client.appends[0][1]

        # Should have the tool usage
        assert "[Used 1 tool: Bash(ls)]" in text

        # And the follow-up text
        assert "Here's what I found" in text


class TestCommandHandling:
    """Tests for slash command transcription."""

    def test_builtin_command_transcribed_simply(self, tmp_path: Path) -> None:
        """Built-in commands like /compact should be transcribed as [User issued /compact command]."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        transcript_path.write_text(
            "\n".join(
                [
                    # Command invocation
                    json.dumps(
                        {
                            "uuid": "cmd1",
                            "parentUuid": None,
                            "type": "user",
                            "timestamp": "2024-01-21T14:30:00Z",
                            "message": {
                                "content": "<command-name>/compact</command-name>\n"
                                "<command-message>compact</command-message>\n"
                                "<command-args></command-args>"
                            },
                        }
                    ),
                    # Command output (should be skipped)
                    json.dumps(
                        {
                            "uuid": "out1",
                            "parentUuid": "cmd1",
                            "type": "user",
                            "timestamp": "2024-01-21T14:30:05Z",
                            "message": {
                                "content": "<local-command-stdout>Compacted</local-command-stdout>"
                            },
                        }
                    ),
                    # Assistant response
                    json.dumps(
                        {
                            "uuid": "resp1",
                            "parentUuid": "out1",
                            "type": "assistant",
                            "timestamp": "2024-01-21T14:30:10Z",
                            "message": {"content": [{"type": "text", "text": "Done."}]},
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        text = client.appends[0][1]

        # Should have the command as a simple notation
        assert "[User issued /compact command]" in text
        # Should NOT have the raw command output
        assert "Compacted" not in text
        assert "<local-command-stdout>" not in text
        # Should have the assistant response
        assert "Done." in text

    def test_custom_command_expansion_skipped(self, tmp_path: Path) -> None:
        """Custom commands like /commit should skip the expanded file content."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        transcript_path.write_text(
            "\n".join(
                [
                    # Command invocation
                    json.dumps(
                        {
                            "uuid": "cmd1",
                            "parentUuid": None,
                            "type": "user",
                            "timestamp": "2024-01-21T14:30:00Z",
                            "message": {
                                "content": "<command-message>commit</command-message>\n"
                                "<command-name>/commit</command-name>"
                            },
                        }
                    ),
                    # Command expansion (the .md file content - should be skipped)
                    json.dumps(
                        {
                            "uuid": "exp1",
                            "parentUuid": "cmd1",
                            "type": "user",
                            "timestamp": "2024-01-21T14:30:05Z",
                            "message": {
                                "content": [
                                    {
                                        "type": "text",
                                        "text": "# /commit\n## Context\n- Current branch: main\n"
                                        "## Task\nClean up and commit...",
                                    }
                                ]
                            },
                        }
                    ),
                    # Assistant response
                    json.dumps(
                        {
                            "uuid": "resp1",
                            "parentUuid": "exp1",
                            "type": "assistant",
                            "timestamp": "2024-01-21T14:30:10Z",
                            "message": {
                                "content": [
                                    {"type": "text", "text": "Committed changes."}
                                ]
                            },
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        text = client.appends[0][1]

        # Should have the command as a simple notation
        assert "[User issued /commit command]" in text
        # Should NOT have the expanded command file content
        assert "# /commit" not in text
        assert "Current branch" not in text
        assert "Clean up and commit" not in text
        # Should have the assistant response
        assert "Committed changes." in text

    def test_command_followed_by_assistant(self, tmp_path: Path) -> None:
        """Command directly followed by assistant (no expansion) should work."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        transcript_path.write_text(
            "\n".join(
                [
                    # Command invocation
                    json.dumps(
                        {
                            "uuid": "cmd1",
                            "parentUuid": None,
                            "type": "user",
                            "timestamp": "2024-01-21T14:30:00Z",
                            "message": {
                                "content": "<command-name>/clear</command-name>\n"
                                "<command-message>clear</command-message>\n"
                                "<command-args></command-args>"
                            },
                        }
                    ),
                    # Assistant responds directly (no user message in between)
                    json.dumps(
                        {
                            "uuid": "resp1",
                            "parentUuid": "cmd1",
                            "type": "assistant",
                            "timestamp": "2024-01-21T14:30:05Z",
                            "message": {
                                "content": [
                                    {"type": "text", "text": "Context cleared."}
                                ]
                            },
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        text = client.appends[0][1]

        # Should have the command
        assert "[User issued /clear command]" in text
        # Should have the assistant response
        assert "Context cleared." in text

    def test_hyphenated_command_cleaned_properly(self, tmp_path: Path) -> None:
        """Commands with hyphens like /review-pr should be cleaned properly."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        transcript_path.write_text(
            "\n".join(
                [
                    # Hyphenated command invocation
                    json.dumps(
                        {
                            "uuid": "cmd1",
                            "parentUuid": None,
                            "type": "user",
                            "timestamp": "2024-01-21T14:30:00Z",
                            "message": {
                                "content": "<command-name>/review-pr</command-name>\n"
                                "<command-message>review-pr</command-message>\n"
                                "<command-args></command-args>"
                            },
                        }
                    ),
                    # Assistant responds
                    json.dumps(
                        {
                            "uuid": "resp1",
                            "parentUuid": "cmd1",
                            "type": "assistant",
                            "timestamp": "2024-01-21T14:30:05Z",
                            "message": {
                                "content": [{"type": "text", "text": "Reviewing PR."}]
                            },
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeTranscriptClient()
        execute_sync(transcript_path, state_path, client)

        text = client.appends[0][1]

        # Should have the hyphenated command
        assert "[User issued /review-pr command]" in text
        # Should NOT have any raw XML
        assert "<command-name>" not in text
        assert "<command-message>" not in text
        assert "Reviewing PR." in text
