"""Tests for transcript formatting and compaction segment batching."""

from __future__ import annotations

import json
from pathlib import Path

from ragzoom.claude_memory.transcript_sync import (
    SessionState,
    execute_sync,
)


class FakeAppendResult:
    """Fake append result that mimics IndexingResult."""

    def __init__(self, span_start: int, span_end: int) -> None:
        self.span_start = span_start
        self.span_end = span_end
        self.chunks_created = 1


class FakeClient:
    """Fake client that tracks appends and returns span positions."""

    def __init__(self) -> None:
        self.appends: list[tuple[str, str]] = []
        self.truncates: list[tuple[str, int]] = []
        self._current_span: int = 0

    def append(self, document_id: str, text: str) -> FakeAppendResult:
        """Append text and return span positions."""
        self.appends.append((document_id, text))
        span_start = self._current_span
        span_end = self._current_span + len(text)
        self._current_span = span_end
        return FakeAppendResult(span_start=span_start, span_end=span_end)

    def truncate(self, document_id: str, span_start: int) -> None:
        """Truncate document to span."""
        self.truncates.append((document_id, span_start))
        self._current_span = span_start


class TestTranscriptFormatting:
    """Tests for transcript formatting issues."""

    def test_double_newlines_between_messages(self, tmp_path: Path) -> None:
        """Messages should be separated by double newlines."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        transcript_path.write_text(
            "\n".join(
                [
                    json.dumps(
                        {
                            "uuid": "msg1",
                            "parentUuid": None,
                            "type": "user",
                            "message": {"content": "First message"},
                        }
                    ),
                    json.dumps(
                        {
                            "uuid": "msg2",
                            "parentUuid": "msg1",
                            "type": "assistant",
                            "message": {
                                "content": [{"type": "text", "text": "Response"}]
                            },
                        }
                    ),
                    json.dumps(
                        {
                            "uuid": "msg3",
                            "parentUuid": "msg2",
                            "type": "user",
                            "message": {"content": "Second message"},
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeClient()
        execute_sync(transcript_path, state_path, client)

        assert len(client.appends) == 1
        combined_text = client.appends[0][1]

        # Should have double newlines between messages
        assert "\n\n[USER]" in combined_text or combined_text.startswith("[USER]")
        assert "\n\n[ASSISTANT]" in combined_text

        # Should NOT have single newline followed by [USER]/[ASSISTANT]
        # (i.e., messages should not be run together)
        lines = combined_text.split("\n")
        for i, line in enumerate(lines):
            if line.startswith("[USER]") or line.startswith("[ASSISTANT]"):
                # Either it's the first line, or preceded by empty line
                if i > 0:
                    assert lines[i - 1] == "", f"Missing blank line before {line}"

    def test_slash_commands_simplified(self, tmp_path: Path) -> None:
        """Slash commands should be simplified from XML format."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        # The XML command format that Claude Code produces
        command_content = (
            "Caveat: The messages below were generated by the user while running "
            "local commands. DO NOT respond to these messages or otherwise consider "
            "them in your response unless the user explicitly asks you to."
            "<command-name>/clear</command-name>"
            "<command-message>clear</command-message>"
            "<command-args></command-args>"
        )

        transcript_path.write_text(
            json.dumps(
                {
                    "uuid": "msg1",
                    "parentUuid": None,
                    "type": "user",
                    "message": {"content": command_content},
                }
            )
            + "\n"
        )

        client = FakeClient()
        execute_sync(transcript_path, state_path, client)

        assert len(client.appends) == 1
        text = client.appends[0][1]

        # Should NOT contain the verbose XML
        assert "<command-name>" not in text
        assert "<command-message>" not in text
        assert "<command-args>" not in text
        assert "Caveat:" not in text

        # Should contain the simplified command
        assert "/clear" in text

    def test_local_stdout_removed(self, tmp_path: Path) -> None:
        """Empty local-command-stdout tags should be removed."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        transcript_path.write_text(
            json.dumps(
                {
                    "uuid": "msg1",
                    "parentUuid": None,
                    "type": "user",
                    "message": {
                        "content": "<local-command-stdout></local-command-stdout>"
                    },
                }
            )
            + "\n"
        )

        client = FakeClient()
        execute_sync(transcript_path, state_path, client)

        # Empty messages should result in no append
        # or if appended, should not contain the tag
        if client.appends:
            text = client.appends[0][1]
            assert "<local-command-stdout>" not in text


class TestCompactionSegmentBatching:
    """Tests for batching at compaction boundaries."""

    def test_one_append_per_compaction_segment(self, tmp_path: Path) -> None:
        """Each compaction segment should be a separate append."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        transcript_path.write_text(
            "\n".join(
                [
                    # First segment (pre-compaction)
                    json.dumps(
                        {
                            "uuid": "a1",
                            "parentUuid": None,
                            "type": "user",
                            "message": {"content": "Segment 1 message 1"},
                        }
                    ),
                    json.dumps(
                        {
                            "uuid": "a2",
                            "parentUuid": "a1",
                            "type": "assistant",
                            "message": {
                                "content": [{"type": "text", "text": "Segment 1 reply"}]
                            },
                        }
                    ),
                    # First compaction boundary
                    json.dumps({"uuid": "sys1", "parentUuid": None, "type": "system"}),
                    json.dumps(
                        {
                            "uuid": "c1",
                            "parentUuid": "sys1",
                            "isCompactSummary": True,
                        }
                    ),
                    # Second segment
                    json.dumps(
                        {
                            "uuid": "b1",
                            "parentUuid": "c1",
                            "type": "user",
                            "message": {"content": "Segment 2 message 1"},
                        }
                    ),
                    json.dumps(
                        {
                            "uuid": "b2",
                            "parentUuid": "b1",
                            "type": "assistant",
                            "message": {
                                "content": [{"type": "text", "text": "Segment 2 reply"}]
                            },
                        }
                    ),
                    # Second compaction boundary
                    json.dumps({"uuid": "sys2", "parentUuid": None, "type": "system"}),
                    json.dumps(
                        {
                            "uuid": "c2",
                            "parentUuid": "sys2",
                            "isCompactSummary": True,
                        }
                    ),
                    # Third segment
                    json.dumps(
                        {
                            "uuid": "d1",
                            "parentUuid": "c2",
                            "type": "user",
                            "message": {"content": "Segment 3 message 1"},
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeClient()
        execute_sync(transcript_path, state_path, client)

        # Should have 3 appends (one per segment)
        assert len(client.appends) == 3

        # First append should contain segment 1 content
        assert "Segment 1" in client.appends[0][1]

        # Second append should contain segment 2 content
        assert "Segment 2" in client.appends[1][1]

        # Third append should contain segment 3 content
        assert "Segment 3" in client.appends[2][1]

    def test_state_has_entry_per_segment(self, tmp_path: Path) -> None:
        """State should have one entry per compaction segment for rollback."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        transcript_path.write_text(
            "\n".join(
                [
                    # First segment
                    json.dumps(
                        {
                            "uuid": "a1",
                            "parentUuid": None,
                            "type": "user",
                            "message": {"content": "First"},
                        }
                    ),
                    # Compaction
                    json.dumps({"uuid": "sys1", "parentUuid": None, "type": "system"}),
                    json.dumps(
                        {"uuid": "c1", "parentUuid": "sys1", "isCompactSummary": True}
                    ),
                    # Second segment
                    json.dumps(
                        {
                            "uuid": "b1",
                            "parentUuid": "c1",
                            "type": "user",
                            "message": {"content": "Second"},
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeClient()
        execute_sync(transcript_path, state_path, client)

        state = SessionState.load(state_path)
        assert state is not None

        # Should have 2 entries (one per segment)
        assert len(state.entries) == 2

        # First entry should be for last UUID in first segment
        assert state.entries[0].last_uuid == "a1"

        # Second entry should be for last UUID in second segment
        assert state.entries[1].last_uuid == "b1"

    def test_compaction_boundary_spans_are_correct(self, tmp_path: Path) -> None:
        """Each segment's span_end should be the boundary for that segment."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        transcript_path.write_text(
            "\n".join(
                [
                    # First segment
                    json.dumps(
                        {
                            "uuid": "a1",
                            "parentUuid": None,
                            "type": "user",
                            "message": {"content": "First segment content"},
                        }
                    ),
                    # Compaction
                    json.dumps({"uuid": "sys1", "parentUuid": None, "type": "system"}),
                    json.dumps(
                        {"uuid": "c1", "parentUuid": "sys1", "isCompactSummary": True}
                    ),
                    # Second segment
                    json.dumps(
                        {
                            "uuid": "b1",
                            "parentUuid": "c1",
                            "type": "user",
                            "message": {"content": "Second segment content"},
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeClient()
        execute_sync(transcript_path, state_path, client)

        state = SessionState.load(state_path)
        assert state is not None
        assert len(state.entries) == 2

        # First segment's span_end should be length of first append
        first_text = client.appends[0][1]
        assert state.entries[0].span_end == len(first_text)

        # Second segment's span_end should be cumulative
        second_text = client.appends[1][1]
        assert state.entries[1].span_end == len(first_text) + len(second_text)


class TestToolUsageBatching:
    """Tests for batching consecutive tool usage messages."""

    def test_tool_only_with_text_between_not_batched(self, tmp_path: Path) -> None:
        """Tool-only messages separated by text messages should not batch."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        # This mirrors real transcript pattern: tool, result, text, tool, result
        transcript_path.write_text(
            "\n".join(
                [
                    # First tool use
                    json.dumps(
                        {
                            "uuid": "msg1",
                            "parentUuid": None,
                            "type": "assistant",
                            "message": {
                                "content": [
                                    {
                                        "type": "tool_use",
                                        "name": "Bash",
                                        "input": {"command": "git status"},
                                    },
                                ]
                            },
                        }
                    ),
                    # Tool result
                    json.dumps(
                        {
                            "uuid": "msg2",
                            "parentUuid": "msg1",
                            "type": "user",
                            "toolUseResult": "output",
                            "message": {"content": "..."},
                        }
                    ),
                    # Text response (breaks the chain)
                    json.dumps(
                        {
                            "uuid": "msg3",
                            "parentUuid": "msg2",
                            "type": "assistant",
                            "message": {
                                "content": [
                                    {"type": "text", "text": "The status shows..."},
                                ]
                            },
                        }
                    ),
                    # Second tool use
                    json.dumps(
                        {
                            "uuid": "msg4",
                            "parentUuid": "msg3",
                            "type": "assistant",
                            "message": {
                                "content": [
                                    {
                                        "type": "tool_use",
                                        "name": "Read",
                                        "input": {"file_path": "README.md"},
                                    },
                                ]
                            },
                        }
                    ),
                    # Tool result
                    json.dumps(
                        {
                            "uuid": "msg5",
                            "parentUuid": "msg4",
                            "type": "user",
                            "toolUseResult": "content",
                            "message": {"content": "..."},
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeClient()
        execute_sync(transcript_path, state_path, client)

        text = client.appends[0][1]

        # Should have two separate tool entries because text message broke the chain
        assert text.count("[Used 1 tool:") == 2
        assert "Bash(git status)" in text
        assert "Read(README.md)" in text
        assert "The status shows" in text

    def test_consecutive_tool_uses_batched(self, tmp_path: Path) -> None:
        """Consecutive tool-only messages should be batched into one line."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        # Simulate consecutive tool-only assistant messages
        transcript_path.write_text(
            "\n".join(
                [
                    # First tool use (tool-only, no text)
                    json.dumps(
                        {
                            "uuid": "msg1",
                            "parentUuid": None,
                            "type": "assistant",
                            "message": {
                                "content": [
                                    {
                                        "type": "tool_use",
                                        "name": "Bash",
                                        "input": {"command": "git status"},
                                    },
                                ]
                            },
                        }
                    ),
                    # Tool result (user type)
                    json.dumps(
                        {
                            "uuid": "msg2",
                            "parentUuid": "msg1",
                            "type": "user",
                            "toolUseResult": "some output",
                            "message": {"content": "..."},
                        }
                    ),
                    # Second tool use (tool-only)
                    json.dumps(
                        {
                            "uuid": "msg3",
                            "parentUuid": "msg2",
                            "type": "assistant",
                            "message": {
                                "content": [
                                    {
                                        "type": "tool_use",
                                        "name": "Read",
                                        "input": {"file_path": "README.md"},
                                    },
                                ]
                            },
                        }
                    ),
                    # Tool result
                    json.dumps(
                        {
                            "uuid": "msg4",
                            "parentUuid": "msg3",
                            "type": "user",
                            "toolUseResult": "file content",
                            "message": {"content": "..."},
                        }
                    ),
                    # Third tool use (tool-only)
                    json.dumps(
                        {
                            "uuid": "msg5",
                            "parentUuid": "msg4",
                            "type": "assistant",
                            "message": {
                                "content": [
                                    {
                                        "type": "tool_use",
                                        "name": "Grep",
                                        "input": {"pattern": "TODO"},
                                    },
                                ]
                            },
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeClient()
        execute_sync(transcript_path, state_path, client)

        assert len(client.appends) == 1
        text = client.appends[0][1]

        # Should have a single batched message with all tool names
        assert "[Used 3 tools:" in text
        assert "Bash(git status)" in text
        assert "Read(README.md)" in text
        assert "Grep(TODO)" in text

        # Should NOT have multiple separate tool lines
        assert text.count("[Used") == 1

    def test_tool_names_include_summary(self, tmp_path: Path) -> None:
        """Tool names should include a brief summary of the invocation."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        transcript_path.write_text(
            "\n".join(
                [
                    json.dumps(
                        {
                            "uuid": "msg1",
                            "parentUuid": None,
                            "type": "assistant",
                            "message": {
                                "content": [
                                    {
                                        "type": "tool_use",
                                        "name": "Bash",
                                        "input": {
                                            "command": "python -m ragzoom.cli query --debug"
                                        },
                                    },
                                ]
                            },
                        }
                    ),
                    json.dumps(
                        {
                            "uuid": "msg2",
                            "parentUuid": "msg1",
                            "type": "user",
                            "toolUseResult": "output",
                            "message": {"content": "..."},
                        }
                    ),
                    json.dumps(
                        {
                            "uuid": "msg3",
                            "parentUuid": "msg2",
                            "type": "assistant",
                            "message": {
                                "content": [
                                    {
                                        "type": "tool_use",
                                        "name": "Read",
                                        "input": {"file_path": "ragzoom/db_utils.py"},
                                    },
                                ]
                            },
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeClient()
        execute_sync(transcript_path, state_path, client)

        text = client.appends[0][1]

        # Should show tool with argument summary
        assert "Bash(python -m ragzoom" in text or "Bash(ragzoom" in text
        assert "Read(ragzoom/db_utils.py)" in text

    def test_single_tool_use_not_batched(self, tmp_path: Path) -> None:
        """A single tool use followed by text should not be batched."""
        transcript_path = tmp_path / "transcript.jsonl"
        state_path = tmp_path / "state.jsonl"

        transcript_path.write_text(
            "\n".join(
                [
                    json.dumps(
                        {
                            "uuid": "msg1",
                            "parentUuid": None,
                            "type": "assistant",
                            "message": {
                                "content": [
                                    {"type": "text", "text": "Let me check."},
                                    {
                                        "type": "tool_use",
                                        "name": "Bash",
                                        "input": {"command": "ls"},
                                    },
                                ]
                            },
                        }
                    ),
                    json.dumps(
                        {
                            "uuid": "msg2",
                            "parentUuid": "msg1",
                            "type": "user",
                            "toolUseResult": "output",
                            "message": {"content": "..."},
                        }
                    ),
                    # Assistant responds with text (breaking the tool-only chain)
                    json.dumps(
                        {
                            "uuid": "msg3",
                            "parentUuid": "msg2",
                            "type": "assistant",
                            "message": {
                                "content": [
                                    {"type": "text", "text": "Here's what I found."},
                                ]
                            },
                        }
                    ),
                ]
            )
            + "\n"
        )

        client = FakeClient()
        execute_sync(transcript_path, state_path, client)

        text = client.appends[0][1]

        # Should have the tool usage
        assert "[Used 1 tool: Bash(ls)]" in text

        # And the follow-up text
        assert "Here's what I found" in text
