"""Transcribe Claude Code JSONL logs into human-readable format."""

from __future__ import annotations

import json
import re
from collections.abc import Iterator
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ragzoom.wrapper import RagZoom


@dataclass
class TranscribeResult:
    """Result of incremental transcription."""

    chunks: list[str]
    """Transcript chunks (each is a [USER] or [ASSISTANT] message)."""

    final_offset: int
    """JSONL byte offset after last parsed record."""

    chars_transcribed: int
    """Total characters in all chunks (for span tracking)."""

    compaction_chars_offset: int | None
    """Chars transcribed up to last compaction (None if no compaction seen)."""


@dataclass
class SyncState:
    """Persisted state for incremental transcript syncing."""

    byte_offset: int
    """JSONL byte offset for resuming parsing."""

    compaction_span_end: int | None = None
    """Span position where last compaction occurred (for pre-compaction queries)."""


# Patterns for system noise in user messages
_CAVEAT_PATTERN = re.compile(
    r"Caveat: The messages below were generated by the user while running local "
    r"commands\. DO NOT respond to these messages or otherwise consider them in "
    r"your response unless the user explicitly asks you to\.\s*",
    re.DOTALL,
)
_COMMAND_PATTERN = re.compile(
    r"<command-name>(/\w+)</command-name>\s*"
    r"<command-message>\w*</command-message>\s*"
    r"<command-args>[^<]*</command-args>\s*",
    re.DOTALL,
)
_LOCAL_STDOUT_PATTERN = re.compile(
    r"<local-command-stdout>[^<]*</local-command-stdout>\s*",
    re.DOTALL,
)


def parse_jsonl(
    path: Path, start_offset: int = 0
) -> Iterator[tuple[dict[str, object], int]]:
    """Parse a JSONL file that may contain embedded newlines in JSON values.

    Automatically skips metadata records (file-history-snapshot) that are
    never useful for any purpose. Compaction summaries (isCompactSummary)
    are yielded so callers can detect compaction boundaries.

    Args:
        path: Path to the JSONL file.
        start_offset: Byte offset to start parsing from. Must be at a valid
            JSON object boundary (typically from a previous parse).

    Yields:
        Tuples of (record, end_offset) where end_offset is the byte position
        after this record.

    Raises:
        json.JSONDecodeError: If start_offset is not at a valid JSON boundary.
    """
    content = path.read_text()
    decoder = json.JSONDecoder()
    pos = start_offset
    while pos < len(content):
        content_slice = content[pos:].lstrip()
        if not content_slice:
            break
        whitespace_skipped = len(content[pos:]) - len(content_slice)
        obj, end = decoder.raw_decode(content_slice)
        pos += whitespace_skipped + end

        # Skip metadata (never useful)
        if obj.get("type") == "file-history-snapshot":
            continue

        yield obj, pos


_HEADER = """# Claude Code Session Transcript

This is a transcript of a conversation between a human user and Claude Code,
an AI coding assistant. The format is:
- [USER] marks human messages
- [ASSISTANT] marks Claude's responses
- [Used N tools] indicates Claude executed tools (file reads, edits, commands, etc.)

---
"""


def transcribe_log(path: Path) -> str:
    """Transcribe an entire Claude Code JSONL log to human-readable format.

    Coalesces tool use chains into single summaries like "[Used 3 tools]".
    """
    parts: list[str] = [_HEADER.strip()]
    pending_tool_count = 0

    def flush_tools() -> None:
        nonlocal pending_tool_count
        if pending_tool_count > 0:
            parts.append(
                f"[Used {pending_tool_count} tool{'s' if pending_tool_count > 1 else ''}]"
            )
            pending_tool_count = 0

    for record, _offset in parse_jsonl(path):
        # Skip compaction summaries (redundant for full transcript)
        if record.get("isCompactSummary"):
            continue

        record_type = record.get("type")

        if record_type == "user":
            if "toolUseResult" in record:
                # Tool result - count it but don't output
                continue
            # Human message - flush any pending tools first
            flush_tools()
            text = _extract_user_text(record)
            if text.strip():
                parts.append(f"[USER]\n{text}")

        elif record_type == "assistant":
            text, tool_count = _extract_assistant_content(record)
            if text.strip():
                flush_tools()
                parts.append(f"[ASSISTANT]\n{text}")
            if tool_count > 0:
                pending_tool_count += tool_count

    flush_tools()
    return "\n\n".join(parts)


def _extract_user_text(record: dict[str, object]) -> str:
    """Extract text content from a user message."""
    message = record.get("message", {})
    if not isinstance(message, dict):
        return str(message)

    content = message.get("content", "")
    if isinstance(content, str):
        return _clean_user_text(content)

    if isinstance(content, list):
        texts = []
        for block in content:
            if isinstance(block, dict) and block.get("type") == "text":
                texts.append(str(block.get("text", "")))
            elif isinstance(block, str):
                texts.append(block)
        return _clean_user_text("".join(texts))

    return _clean_user_text(str(content))


def _clean_user_text(text: str) -> str:
    """Clean system noise from user text, transforming commands to simple format."""
    # Remove caveat boilerplate
    text = _CAVEAT_PATTERN.sub("", text)

    # Transform <command-name>/foo</command-name>... to just /foo
    text = _COMMAND_PATTERN.sub(r"\1", text)

    # Remove empty local-command-stdout tags
    text = _LOCAL_STDOUT_PATTERN.sub("", text)

    return text.strip()


def _extract_assistant_content(record: dict[str, object]) -> tuple[str, int]:
    """Extract text and tool count from an assistant message.

    Returns (text_content, tool_use_count).
    """
    message = record.get("message", {})
    if not isinstance(message, dict):
        return str(message), 0

    content = message.get("content", [])
    if not isinstance(content, list):
        return str(content), 0

    texts: list[str] = []
    tool_count = 0

    for block in content:
        if not isinstance(block, dict):
            continue

        block_type = block.get("type")
        if block_type == "text":
            text = block.get("text", "")
            if isinstance(text, str) and text.strip():
                texts.append(text)
        elif block_type == "tool_use":
            tool_count += 1

    return "\n\n".join(texts), tool_count


def _get_state_path(doc_id: str) -> Path:
    """Get the path to the state file for a document."""
    state_dir = Path("data/transcript-state")
    state_dir.mkdir(parents=True, exist_ok=True)
    return state_dir / f"{doc_id}.json"


def _load_state(doc_id: str) -> SyncState:
    """Load sync state for a document. Returns default state if not found."""
    state_path = _get_state_path(doc_id)
    if state_path.exists():
        data = json.loads(state_path.read_text())
        if isinstance(data, dict) and "byte_offset" in data:
            return SyncState(
                byte_offset=int(data["byte_offset"]),
                compaction_span_end=data.get("compaction_span_end"),
            )
    return SyncState(byte_offset=0)


def _save_state(doc_id: str, state: SyncState) -> None:
    """Save sync state for a document."""
    state_path = _get_state_path(doc_id)
    data = {"byte_offset": state.byte_offset}
    if state.compaction_span_end is not None:
        data["compaction_span_end"] = state.compaction_span_end
    state_path.write_text(json.dumps(data))


def transcribe_incremental(
    path: Path, start_offset: int = 0, skip_leading_tool_results: bool = True
) -> TranscribeResult:
    """Transcribe new records from a JSONL log into chunks.

    Detects compaction summaries and reports when one is encountered, allowing
    callers to track the compaction boundary in transcript coordinates.

    Args:
        path: Path to the JSONL file.
        start_offset: Byte offset to start parsing from.
        skip_leading_tool_results: If True, skip toolUseResult records at the start
            (orphaned from a previous sync).

    Returns:
        TranscribeResult with chunks, final offset, character count, and
        compaction detection flag.
    """
    chunks: list[str] = []
    pending_tool_count = 0
    final_offset = start_offset
    skipping_leading_tools = skip_leading_tool_results
    compaction_chars_offset: int | None = None

    def current_chars() -> int:
        """Calculate chars transcribed so far (including separators)."""
        total = sum(len(chunk) for chunk in chunks)
        if len(chunks) > 1:
            total += 2 * (len(chunks) - 1)
        return total

    def flush_tools() -> None:
        nonlocal pending_tool_count
        if pending_tool_count > 0:
            chunks.append(
                f"[Used {pending_tool_count} tool{'s' if pending_tool_count > 1 else ''}]"
            )
            pending_tool_count = 0

    for record, offset in parse_jsonl(path, start_offset):
        final_offset = offset

        # Detect compaction - record chars transcribed up to this point
        if record.get("isCompactSummary"):
            compaction_chars_offset = current_chars()
            continue

        record_type = record.get("type")

        if record_type == "user":
            if "toolUseResult" in record:
                if skipping_leading_tools:
                    # Skip orphaned tool results from previous sync
                    continue
                # Otherwise just ignore (we don't output tool results)
                continue
            # Real user message - stop skipping
            skipping_leading_tools = False
            flush_tools()
            text = _extract_user_text(record)
            if text.strip():
                chunks.append(f"[USER]\n{text}")

        elif record_type == "assistant":
            skipping_leading_tools = False
            text, tool_count = _extract_assistant_content(record)
            if text.strip():
                flush_tools()
                chunks.append(f"[ASSISTANT]\n{text}")
            if tool_count > 0:
                pending_tool_count += tool_count

    flush_tools()

    return TranscribeResult(
        chunks=chunks,
        final_offset=final_offset,
        chars_transcribed=current_chars(),
        compaction_chars_offset=compaction_chars_offset,
    )


def sync_transcript(jsonl_path: Path, doc_id: str, client: RagZoom) -> int:
    """Sync a Claude Code JSONL log to a RagZoom document.

    Incrementally transcribes new records and appends them to the document.
    Handles document deletion by resetting state and starting fresh.
    Tracks compaction boundaries for pre-compaction queries.

    Args:
        jsonl_path: Path to the JSONL log file.
        doc_id: Document ID in RagZoom.
        client: The RagZoom client wrapper.

    Returns:
        Number of new chunks appended.
    """
    # Load state
    state = _load_state(doc_id)

    # Check if document exists by trying to query it
    # If we have state but document is gone, reset
    doc_exists = _document_exists(client, doc_id)
    if not doc_exists and state.byte_offset > 0:
        # Document was deleted, start fresh
        state = SyncState(byte_offset=0)

    # Get current document length for compaction boundary calculation
    indexed_length = 0
    if doc_exists:
        indexed_length = _get_document_length(client, doc_id)

    # Transcribe new content
    result = transcribe_incremental(
        jsonl_path,
        start_offset=state.byte_offset,
        skip_leading_tool_results=(state.byte_offset > 0),
    )

    if not result.chunks:
        return 0

    # Join chunks into text for the RagZoom API
    text = "\n\n".join(result.chunks)

    # Create or append
    if not doc_exists:
        # First run - prepend header
        header_text = _HEADER.strip() + "\n\n"
        text = header_text + text
        client.index(doc_id, text)
        # Account for header in compaction offset
        header_len = len(header_text)
    else:
        client.append(doc_id, text)
        header_len = 0

    # If compaction detected, record the boundary
    # indexed_length (existing doc) + header (if first run) + chars up to compaction
    if result.compaction_chars_offset is not None:
        state.compaction_span_end = (
            indexed_length + header_len + result.compaction_chars_offset
        )

    # Update and save state
    state.byte_offset = result.final_offset
    _save_state(doc_id, state)

    return len(result.chunks)


def _document_exists(client: RagZoom, doc_id: str) -> bool:
    """Check if a document exists in RagZoom."""
    try:
        with client._client() as grpc_client:
            status = grpc_client.get_document_status(doc_id)
            return status.leaf_count > 0
    except Exception:
        return False


def _get_document_length(client: RagZoom, doc_id: str) -> int:
    """Get the current document length (span_end of last node in tiling).

    Queries with minimal parameters to get just the forest roots, then takes
    the span_end of the last node (tiling is span-ordered).
    """
    with client._client() as grpc_client:
        output = grpc_client.execute_query(
            query="",  # Empty query, just get roots
            document_id=doc_id,
            budget_tokens=None,
            num_seeds=0,
            embedding_model=None,
            debug=False,
            viz_width=80,
            use_token_coords=False,
        )
        tiling_ids = output.retrieval.tiling_ids
        if not tiling_ids:
            return 0
        last_node = output.retrieval.nodes[tiling_ids[-1]]
        return last_node.span_end
