#!/usr/bin/env bash
set -euo pipefail

# Update tests/slowtests.txt by profiling test durations and selecting those over a threshold.
# Usage: scripts/update-slow-tests.sh [--threshold SECONDS]
# Default threshold: 0.2 seconds

THRESH=0.2
if [[ "${1:-}" == "--threshold" && -n "${2:-}" ]]; then
  THRESH="$2"
fi

out_file="tests/slowtests.txt"
tmp_file="$(mktemp)"
trap 'rm -f "$tmp_file"' EXIT

echo "Profiling tests to identify slow tests (> ${THRESH}s)..." >&2

# Run full test suite (excluding benchmarks) with durations for all tests
# We parse 'call' durations only, ignoring setup/teardown noise.
pytest -q --durations=0 -k 'not benchmarks' 2>&1 | tee "$tmp_file" >/dev/null || true

awk -v thr="$THRESH" '
  /call[[:space:]]+tests\// {
    # Example: "0.50s call     tests/...::..."
    # Extract seconds and nodeid
    sec=$1; gsub("s","",sec);
    # nodeid after the word "call"
    line=$0
    sub(/.*call[[:space:]]+/, "", line)
    if (sec+0 > thr+0) {
      print line
    }
  }
' "$tmp_file" | sort -u > "$tmp_file.slow"

{
  echo "## Slow tests (nodeid prefixes). Generated by scripts/update-slow-tests.sh."
  echo "## Edit by hand or regenerate with the script."
  echo
  while IFS= read -r nid; do
    [[ -n "$nid" ]] && echo "$nid"
  done < "$tmp_file.slow"
} > "$out_file"

echo "Updated $out_file with $(wc -l < "$tmp_file.slow") slow tests (threshold=${THRESH}s)." >&2
